//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agentes
    {
        public string empresa { get; set; }
        public string fkcuentas { get; set; }
        public string fktipoirpf { get; set; }
        public string fkregimeniva { get; set; }
        public Nullable<int> fkformapago { get; set; }
        public Nullable<double> porcentajecomision { get; set; }
        public Nullable<double> comisionporm2 { get; set; }
        public Nullable<double> comisionporm3 { get; set; }
        public Nullable<double> porcentajeincrementosobreptb { get; set; }
        public Nullable<double> primaincrementosobreptb { get; set; }
        public Nullable<double> porcentajedecrementosobreptb { get; set; }
        public Nullable<double> primadecrementosobreptb { get; set; }
    }
}
