//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmacenesZona
    {
        public string empresa { get; set; }
        public string fkalmacenes { get; set; }
        public int id { get; set; }
        public string descripcion { get; set; }
        public string fktipoubicacion { get; set; }
        public string coordenadas { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
    }
}
