//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosTercero
    {
        public string empresa { get; set; }
        public string codarticulo { get; set; }
        public int id { get; set; }
        public string codtercero { get; set; }
        public string descripciontercero { get; set; }
        public string codarticulotercero { get; set; }
        public string descripcionarticulotercero { get; set; }
    
        public virtual Articulos Articulos { get; set; }
    }
}
