//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosComponentes
    {
        public string empresa { get; set; }
        public string fkarticulo { get; set; }
        public int id { get; set; }
        public string idcomponente { get; set; }
        public string descripcioncomponente { get; set; }
        public Nullable<int> piezas { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> ancho { get; set; }
        public Nullable<double> grueso { get; set; }
        public Nullable<int> merma { get; set; }
    
        public virtual Articulos Articulos { get; set; }
    }
}
