//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancosMandatos
    {
        public string empresa { get; set; }
        public string fkcuentas { get; set; }
        public string id { get; set; }
        public string descripcion { get; set; }
        public string fkpaises { get; set; }
        public string iban { get; set; }
        public string bic { get; set; }
        public string sufijoacreedor { get; set; }
        public string contratoconfirmig { get; set; }
        public string contadorconfirming { get; set; }
        public string direccion { get; set; }
        public string cpostal { get; set; }
        public string ciudad { get; set; }
        public string fkprovincias { get; set; }
        public string telefonobanco { get; set; }
        public string personacontacto { get; set; }
        public string idmandato { get; set; }
        public string idacreedor { get; set; }
        public Nullable<int> tiposecuenciasepa { get; set; }
        public Nullable<int> tipoadeudo { get; set; }
        public Nullable<double> importemandato { get; set; }
        public Nullable<int> recibosmandato { get; set; }
        public Nullable<double> importelimiterecibo { get; set; }
        public Nullable<System.DateTime> fechafirma { get; set; }
        public Nullable<System.DateTime> fechaexpiracion { get; set; }
        public Nullable<System.DateTime> fechaultimaremesa { get; set; }
        public Nullable<double> importeremesados { get; set; }
        public Nullable<int> recibosremesados { get; set; }
        public string devolvera { get; set; }
        public string notas { get; set; }
        public Nullable<bool> defecto { get; set; }
        public Nullable<bool> finalizado { get; set; }
        public Nullable<int> esquema { get; set; }
        public Nullable<bool> bloqueada { get; set; }
        public string fkMotivosbloqueo { get; set; }
        public Nullable<System.DateTime> fechamodificacionbloqueo { get; set; }
        public Nullable<System.Guid> fkUsuariobloqueo { get; set; }
        public string riesgonacional { get; set; }
        public string riesgoextranjero { get; set; }
    }
}
