//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class BundleLin
    {
        public string empresa { get; set; }
        public string fkbundlelote { get; set; }
        public string fkbundle { get; set; }
        public int id { get; set; }
        public string lote { get; set; }
        public string loteid { get; set; }
        public string fkarticulos { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> coste { get; set; }
        public Nullable<double> largo { get; set; }
        public Nullable<double> ancho { get; set; }
        public Nullable<double> grueso { get; set; }
        public Nullable<double> metros { get; set; }
        public Nullable<double> cantidad { get; set; }
        public string fkunidades { get; set; }
        public int decimalesunidades { get; set; }
        public int decimalesprecio { get; set; }
        public string fkalmacenes { get; set; }
    
        public virtual Bundle Bundle { get; set; }
    }
}
