//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuraciongraficas
    {
        public string empresa { get; set; }
        public int id { get; set; }
        public System.Guid usuario { get; set; }
        public string idlistado { get; set; }
        public string titulo { get; set; }
        public string agruparpor { get; set; }
        public string valores { get; set; }
        public Nullable<int> intervalotemporal { get; set; }
        public Nullable<bool> apareceinicio { get; set; }
        public int tipografica { get; set; }
        public string filtros { get; set; }
    }
}
