//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuraciongraficas
    {
        public string empresa { get; set; }
        public int id { get; set; }
        public System.Guid usuario { get; set; }
        public string idlistado { get; set; }
        public string titulo { get; set; }
        public string agruparpor { get; set; }
        public string valores { get; set; }
        public Nullable<int> intervalotemporal { get; set; }
        public Nullable<bool> apareceinicio { get; set; }
        public int tipografica { get; set; }
        public string filtros { get; set; }
    }
}
