//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContadoresContabilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContadoresContabilidad()
        {
            this.ContadoresContabilidadLin = new HashSet<ContadoresContabilidadLin>();
        }
    
        public string empresa { get; set; }
        public string id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tipoinicio { get; set; }
        public Nullable<int> primerdocumento { get; set; }
        public Nullable<int> tipocontador { get; set; }
        public int tipodocumento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContadoresContabilidadLin> ContadoresContabilidadLin { get; set; }
    }
}
