//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContadoresContabilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContadoresContabilidad()
        {
            this.ContadoresContabilidadLin = new HashSet<ContadoresContabilidadLin>();
        }
    
        public string empresa { get; set; }
        public string id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tipoinicio { get; set; }
        public Nullable<int> primerdocumento { get; set; }
        public Nullable<int> tipocontador { get; set; }
        public int tipodocumento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContadoresContabilidadLin> ContadoresContabilidadLin { get; set; }
    }
}
