//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public string empresa { get; set; }
        public int tipotercero { get; set; }
        public string fkentidad { get; set; }
        public int id { get; set; }
        public string nombre { get; set; }
        public string fktipocontacto { get; set; }
        public string fkcargoempresa { get; set; }
        public string fkidioma { get; set; }
        public string telefono { get; set; }
        public string telefonomovil { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string nifcif { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> fktipodireccion_direccion { get; set; }
        public string fkentidad_direccion { get; set; }
        public Nullable<int> fkid_direccion { get; set; }
        public string fktipoidentificacion_nif { get; set; }
    }
}
