//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostesVariablesPeriodo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CostesVariablesPeriodo()
        {
            this.CostesVariablesPeriodoLin = new HashSet<CostesVariablesPeriodoLin>();
        }
    
        public string empresa { get; set; }
        public int fkejercicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostesVariablesPeriodoLin> CostesVariablesPeriodoLin { get; set; }
        public virtual Ejercicios Ejercicios { get; set; }
    }
}
