//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public string empresa { get; set; }
        public int tipotercero { get; set; }
        public string fkentidad { get; set; }
        public int id { get; set; }
        public Nullable<bool> defecto { get; set; }
        public string descripcion { get; set; }
        public string fktipovia { get; set; }
        public string direccion { get; set; }
        public string poblacion { get; set; }
        public string cp { get; set; }
        public string fkpais { get; set; }
        public string fkprovincia { get; set; }
        public string personacontacto { get; set; }
        public string telefono { get; set; }
        public string telefonomovil { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public string notas { get; set; }
        public string fktipodireccion { get; set; }
    }
}
