//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejercicios
    {
        public string empresa { get; set; }
        public int id { get; set; }
        public string descripcion { get; set; }
        public string descripcioncorta { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> contabilidadcerradahasta { get; set; }
        public Nullable<System.DateTime> registroivacerradohasta { get; set; }
        public Nullable<int> criterioiva { get; set; }
        public Nullable<int> fkejercicios { get; set; }
        public string fkseriescontables { get; set; }
    
        public virtual CostesVariablesPeriodo CostesVariablesPeriodo { get; set; }
    }
}
