//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejercicios
    {
        public string empresa { get; set; }
        public int id { get; set; }
        public string descripcion { get; set; }
        public string descripcioncorta { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> contabilidadcerradahasta { get; set; }
        public Nullable<System.DateTime> registroivacerradohasta { get; set; }
        public Nullable<int> criterioiva { get; set; }
        public Nullable<int> fkejercicios { get; set; }
        public string fkseriescontables { get; set; }
    
        public virtual CostesVariablesPeriodo CostesVariablesPeriodo { get; set; }
    }
}
