//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasVencimientos
    {
        public string empresa { get; set; }
        public int fkfacturas { get; set; }
        public int id { get; set; }
        public Nullable<int> diasvencimiento { get; set; }
        public Nullable<System.DateTime> fechavencimiento { get; set; }
        public Nullable<double> importevencimiento { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
