//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familiasproductos
    {
        public string empresa { get; set; }
        public string id { get; set; }
        public string descripcion { get; set; }
        public string descripcion2 { get; set; }
        public string descripcionabreviada { get; set; }
        public string fkcontador { get; set; }
        public string fkguiascontables { get; set; }
        public Nullable<int> tipofamilia { get; set; }
        public Nullable<bool> gestionstock { get; set; }
        public Nullable<bool> articulonegocio { get; set; }
        public string fkunidadesmedida { get; set; }
        public Nullable<bool> editarlargo { get; set; }
        public Nullable<bool> editarancho { get; set; }
        public Nullable<bool> editargrueso { get; set; }
        public Nullable<bool> validarmaterial { get; set; }
        public Nullable<bool> validarcaracteristica { get; set; }
        public Nullable<bool> validargrosor { get; set; }
        public Nullable<bool> validaracabado { get; set; }
        public string descripcion1generada { get; set; }
        public string descripcion2generada { get; set; }
        public string descripcionabreviadagenerada { get; set; }
        public string fkgruposiva { get; set; }
        public Nullable<int> tipogestionlotes { get; set; }
        public Nullable<bool> stocknegativoautorizado { get; set; }
        public Nullable<double> existenciasminimasmetros { get; set; }
        public Nullable<double> existenciasmaximasmetros { get; set; }
        public Nullable<double> existenciasminimasunidades { get; set; }
        public Nullable<double> existenciasmaximasunidades { get; set; }
        public Nullable<bool> web { get; set; }
        public Nullable<bool> gestionarcaducidad { get; set; }
        public bool lotefraccionable { get; set; }
        public int categoria { get; set; }
        public Nullable<double> minlargo { get; set; }
        public Nullable<double> maxlargo { get; set; }
        public Nullable<double> minancho { get; set; }
        public Nullable<double> maxancho { get; set; }
        public Nullable<double> mingrueso { get; set; }
        public Nullable<double> maxgrueso { get; set; }
        public Nullable<bool> validardimensiones { get; set; }
        public Nullable<bool> consumibles { get; set; }
        public string clasificacion { get; set; }
        public Nullable<System.Guid> fkcarpetas { get; set; }
    }
}
