//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grosores
    {
        public string empresa { get; set; }
        public string id { get; set; }
        public Nullable<double> grosor { get; set; }
        public string descripcion { get; set; }
        public string descripcion2 { get; set; }
        public string descripcionabreviada { get; set; }
        public Nullable<double> coficientecortabloques { get; set; }
        public Nullable<double> coeficientetelares { get; set; }
    }
}
