//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiascontablesLin
    {
        public string empresa { get; set; }
        public string fkguiascontables { get; set; }
        public int id { get; set; }
        public string fkregimeniva { get; set; }
        public string fkcuentascompras { get; set; }
        public string fkcuentasventas { get; set; }
        public string fkcuentasdevolucioncompras { get; set; }
        public string fkcuentasdevolucionventas { get; set; }
    
        public virtual Guiascontables Guiascontables { get; set; }
    }
}
