//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencias
    {
        public string empresa { get; set; }
        public string id { get; set; }
        public string descripcion { get; set; }
        public int tipomaterial { get; set; }
        public Nullable<int> documento { get; set; }
        public string fkgrupo { get; set; }
    }
}
