//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoStockValorado
    {
        public string Cod__Artículo { get; set; }
        public string Artículo { get; set; }
        public string Familia { get; set; }
        public string Material { get; set; }
        public string Familia_material { get; set; }
        public string Lote { get; set; }
        public string Tipo_de_Lote { get; set; }
        public string Tabla { get; set; }
        public double Cant__Disponible { get; set; }
        public double L { get; set; }
        public double A { get; set; }
        public double G { get; set; }
        public Nullable<double> Metros { get; set; }
        public string UM { get; set; }
        public int C_decimales { get; set; }
        public double PrecioNetoCompra { get; set; }
        public double CosteTotal { get; set; }
        public double PrecioNetoCompraUM { get; set; }
        public double CosteTotalUM { get; set; }
    }
}
