//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoStockValorado
    {
        public string Cod__Artículo { get; set; }
        public string Artículo { get; set; }
        public string Familia { get; set; }
        public string Material { get; set; }
        public string Familia_material { get; set; }
        public string Lote { get; set; }
        public string Tipo_de_Lote { get; set; }
        public string Tabla { get; set; }
        public double Cant__Disponible { get; set; }
        public double L { get; set; }
        public double A { get; set; }
        public double G { get; set; }
        public Nullable<double> Metros { get; set; }
        public string UM { get; set; }
        public int C_decimales { get; set; }
        public double PrecioNetoCompra { get; set; }
        public double CosteTotal { get; set; }
        public double PrecioNetoCompraUM { get; set; }
        public double CosteTotalUM { get; set; }
    }
}
