//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialesLin
    {
        public string empresa { get; set; }
        public string fkmateriales { get; set; }
        public string codigovariedad { get; set; }
        public string descripcion { get; set; }
        public string descripcion2 { get; set; }
    
        public virtual Materiales Materiales { get; set; }
    }
}
