//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiales()
        {
            this.MaterialesLin = new HashSet<MaterialesLin>();
        }
    
        public string empresa { get; set; }
        public string id { get; set; }
        public string descripcion { get; set; }
        public string descripcion2 { get; set; }
        public string descripcionabreviada { get; set; }
        public string fkfamiliamateriales { get; set; }
        public string fkgruposmateriales { get; set; }
        public string dureza { get; set; }
        public Nullable<System.Guid> fkcarpetas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialesLin> MaterialesLin { get; set; }
    }
}
