//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosCostesFabricacion
    {
        public string empresa { get; set; }
        public int fkpedido { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string fkoperario { get; set; }
        public string fktarea { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
    }
}
