//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrevisionesCartera
    {
        public string empresa { get; set; }
        public int id { get; set; }
        public int codvencimiento { get; set; }
        public int codcartera { get; set; }
        public Nullable<double> imputado { get; set; }
    
        public virtual CarteraVencimientos CarteraVencimientos { get; set; }
        public virtual Vencimientos Vencimientos { get; set; }
    }
}
