//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegimenIva
    {
        public string empresa { get; set; }
        public string id { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> normal { get; set; }
        public Nullable<bool> recargo { get; set; }
        public Nullable<bool> exportacion { get; set; }
        public Nullable<bool> exentotasa { get; set; }
        public Nullable<bool> operacionue { get; set; }
        public Nullable<bool> inversionsujetopasivo { get; set; }
        public Nullable<bool> operacionesnosujetas { get; set; }
        public Nullable<bool> zonaespecial { get; set; }
        public Nullable<bool> canariasigic { get; set; }
        public Nullable<bool> extranjero { get; set; }
        public Nullable<bool> ivadiferido { get; set; }
        public Nullable<bool> ivaimportacion { get; set; }
        public Nullable<int> incompatiblecriteriocaja { get; set; }
        public Nullable<int> soportadorepercutidoambos { get; set; }
        public Nullable<bool> bieninversion { get; set; }
        public Nullable<bool> exentosventas { get; set; }
        public string claveoperacion340 { get; set; }
        public Nullable<bool> incluirmodelo347 { get; set; }
        public string tipofacturaemitida { get; set; }
        public string regimenespecialemitida { get; set; }
        public string tipofacturarecibida { get; set; }
        public string regimenespecialrecibida { get; set; }
    }
}
