//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldosAcomuladosPeriodos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaldosAcomuladosPeriodos()
        {
            this.SaldosAcumuladosPeriodosLin = new HashSet<SaldosAcumuladosPeriodosLin>();
        }
    
        public int Id { get; set; }
        public string Empresa { get; set; }
        public int Ejercicio { get; set; }
        public string Usuario { get; set; }
        public string Settings { get; set; }
        public string EnProceso { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Recalculo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaldosAcumuladosPeriodosLin> SaldosAcumuladosPeriodosLin { get; set; }
    }
}
