//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldosAcumuladosPeriodosLin
    {
        public int Id { get; set; }
        public int SalAcomPerId { get; set; }
        public string Cuenta { get; set; }
        public int Nivel { get; set; }
        public decimal ImporteDebeEjercicioActual { get; set; }
        public decimal ImporteHaberEjercicioActual { get; set; }
        public decimal ImporteDebeEjercicioAnterior { get; set; }
        public decimal ImporteHaberEjercicioAnterior { get; set; }
    }
}
