//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientosCorreo
    {
        public string empresa { get; set; }
        public int fkseguimientos { get; set; }
        public string fkorigen { get; set; }
        public int id { get; set; }
        public string correo { get; set; }
        public string asunto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Seguimientos Seguimientos { get; set; }
    }
}
