//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientosCorreo
    {
        public string empresa { get; set; }
        public int fkseguimientos { get; set; }
        public string fkorigen { get; set; }
        public int id { get; set; }
        public string correo { get; set; }
        public string asunto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Seguimientos Seguimientos { get; set; }
    }
}
