//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tareas()
        {
            this.TareasLin = new HashSet<TareasLin>();
        }
    
        public string empresa { get; set; }
        public string id { get; set; }
        public string descripcion { get; set; }
        public string seccionproduccion { get; set; }
        public int imputacion { get; set; }
        public Nullable<double> capacidad { get; set; }
        public Nullable<double> precio { get; set; }
        public int unidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareasLin> TareasLin { get; set; }
    }
}
