//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposIva
    {
        public string empresa { get; set; }
        public string id { get; set; }
        public string nombre { get; set; }
        public string fkgruposiva { get; set; }
        public Nullable<double> porcentajeiva { get; set; }
        public Nullable<double> porcentajerecargoequivalente { get; set; }
        public string fkcuentasivasoportado { get; set; }
        public string fkcuentasivarepercutido { get; set; }
        public string fkcuentasivanodeducible { get; set; }
        public string fkcuentasrecargoequivalenciarepercutido { get; set; }
        public string fkcuentasivasoportadocriteriocaja { get; set; }
        public string fkcuentasivarepercutidocriteriocaja { get; set; }
        public string fkcuentasrecargoequivalenciarepercutidocriteriocaja { get; set; }
        public Nullable<bool> ivasoportado { get; set; }
        public Nullable<bool> ivadeducible { get; set; }
        public Nullable<double> porcentajededucible { get; set; }
    }
}
