//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuariosactivos
    {
        public System.Guid fkusuarios { get; set; }
        public System.Guid idconexion { get; set; }
        public System.DateTime fechaconexion { get; set; }
        public System.DateTime fechaultimaoperacion { get; set; }
        public string ip { get; set; }
    }
}
