//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Dom.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuariosactivos
    {
        public System.Guid fkusuarios { get; set; }
        public System.Guid idconexion { get; set; }
        public System.DateTime fechaconexion { get; set; }
        public System.DateTime fechaultimaoperacion { get; set; }
        public string ip { get; set; }
    }
}
