//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArticulosComponentes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArticulosComponentes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.ArticulosComponentes", typeof(ArticulosComponentes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho.
        /// </summary>
        public static string Ancho {
            get {
                return ResourceManager.GetString("Ancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente.
        /// </summary>
        public static string ArticuloComponente {
            get {
                return ResourceManager.GetString("ArticuloComponente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string DescripcionComponente {
            get {
                return ResourceManager.GetString("DescripcionComponente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articulo.
        /// </summary>
        public static string FkArticulo {
            get {
                return ResourceManager.GetString("FkArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grueso.
        /// </summary>
        public static string Grueso {
            get {
                return ResourceManager.GetString("Grueso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largo.
        /// </summary>
        public static string Largo {
            get {
                return ResourceManager.GetString("Largo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merma %.
        /// </summary>
        public static string Merma {
            get {
                return ResourceManager.GetString("Merma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piezas.
        /// </summary>
        public static string Piezas {
            get {
                return ResourceManager.GetString("Piezas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componentes.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
