//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BancosMandatos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BancosMandatos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.BancosMandatos", typeof(BancosMandatos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos.
        /// </summary>
        public static string Bancos {
            get {
                return ResourceManager.GetString("Bancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC.
        /// </summary>
        public static string Bic {
            get {
                return ResourceManager.GetString("Bic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string Bloqueado {
            get {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contador confirming.
        /// </summary>
        public static string Contadorconfirming {
            get {
                return ResourceManager.GetString("Contadorconfirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato confirming.
        /// </summary>
        public static string Contratoconfirmig {
            get {
                return ResourceManager.GetString("Contratoconfirmig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C. Postal.
        /// </summary>
        public static string Cpostal {
            get {
                return ResourceManager.GetString("Cpostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del banco.
        /// </summary>
        public static string DatosBanco {
            get {
                return ResourceManager.GetString("DatosBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defecto.
        /// </summary>
        public static string Defecto {
            get {
                return ResourceManager.GetString("Defecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devolver a.
        /// </summary>
        public static string Devolvera {
            get {
                return ResourceManager.GetString("Devolvera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esquema.
        /// </summary>
        public static string Esquema {
            get {
                return ResourceManager.GetString("Esquema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de expiración.
        /// </summary>
        public static string Fechaexpiracion {
            get {
                return ResourceManager.GetString("Fechaexpiracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de la firma.
        /// </summary>
        public static string Fechafirma {
            get {
                return ResourceManager.GetString("Fechafirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de la última remesa.
        /// </summary>
        public static string Fechaultimaremesa {
            get {
                return ResourceManager.GetString("Fechaultimaremesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado.
        /// </summary>
        public static string Finalizado {
            get {
                return ResourceManager.GetString("Finalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string Fkcuentas {
            get {
                return ResourceManager.GetString("Fkcuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Fkpaises {
            get {
                return ResourceManager.GetString("Fkpaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Fkprovincias {
            get {
                return ResourceManager.GetString("Fkprovincias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string Iban {
            get {
                return ResourceManager.GetString("Iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id. Acreedor.
        /// </summary>
        public static string Idacreedor {
            get {
                return ResourceManager.GetString("Idacreedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id. Mandato.
        /// </summary>
        public static string Idmandato {
            get {
                return ResourceManager.GetString("Idmandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe límite recibo.
        /// </summary>
        public static string Importelimiterecibo {
            get {
                return ResourceManager.GetString("Importelimiterecibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe mandato.
        /// </summary>
        public static string Importemandato {
            get {
                return ResourceManager.GetString("Importemandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe remesados.
        /// </summary>
        public static string Importeremesados {
            get {
                return ResourceManager.GetString("Importeremesados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatos.
        /// </summary>
        public static string Mandatos {
            get {
                return ResourceManager.GetString("Mandatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Notas {
            get {
                return ResourceManager.GetString("Notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona de contacto.
        /// </summary>
        public static string Personacontacto {
            get {
                return ResourceManager.GetString("Personacontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibos mandato.
        /// </summary>
        public static string Recibosmandato {
            get {
                return ResourceManager.GetString("Recibosmandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibos remesados.
        /// </summary>
        public static string Recibosremesados {
            get {
                return ResourceManager.GetString("Recibosremesados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remesas.
        /// </summary>
        public static string Remesas {
            get {
                return ResourceManager.GetString("Remesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riesgo extranjero.
        /// </summary>
        public static string Riesgoextranjero {
            get {
                return ResourceManager.GetString("Riesgoextranjero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riesgo nacional.
        /// </summary>
        public static string Riesgonacional {
            get {
                return ResourceManager.GetString("Riesgonacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sufijo acreedor.
        /// </summary>
        public static string Sufijoacreedor {
            get {
                return ResourceManager.GetString("Sufijoacreedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono banco.
        /// </summary>
        public static string Telefonobanco {
            get {
                return ResourceManager.GetString("Telefonobanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de adeudo.
        /// </summary>
        public static string Tipoadeudo {
            get {
                return ResourceManager.GetString("Tipoadeudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adeudo recurrente.
        /// </summary>
        public static string TipoAdeudoAdeudoRecurrente {
            get {
                return ResourceManager.GetString("TipoAdeudoAdeudoRecurrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer adeudo recurrente.
        /// </summary>
        public static string TipoAdeudoPrimerAdeudoRecurrente {
            get {
                return ResourceManager.GetString("TipoAdeudoPrimerAdeudoRecurrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último adeudo recurrente.
        /// </summary>
        public static string TipoAdeudoUltimoAdeudoRecurrente {
            get {
                return ResourceManager.GetString("TipoAdeudoUltimoAdeudoRecurrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Único.
        /// </summary>
        public static string TipoAdeudoUnico {
            get {
                return ResourceManager.GetString("TipoAdeudoUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandato.
        /// </summary>
        public static string TipoBancosMandatosMandato {
            get {
                return ResourceManager.GetString("TipoBancosMandatosMandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco.
        /// </summary>
        public static string TiposBancosMandatosBanco {
            get {
                return ResourceManager.GetString("TiposBancosMandatosBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secuencia SEPA.
        /// </summary>
        public static string Tiposecuenciasepa {
            get {
                return ResourceManager.GetString("Tiposecuenciasepa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periódico.
        /// </summary>
        public static string TipoSecuenciaSepaPeriodico {
            get {
                return ResourceManager.GetString("TipoSecuenciaSepaPeriodico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Único.
        /// </summary>
        public static string TipoSecuenciaSepaUnico {
            get {
                return ResourceManager.GetString("TipoSecuenciaSepaUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos y mandatos.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
