//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ejercicios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ejercicios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Ejercicios", typeof(Ejercicios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contabilidad cerrada hasta.
        /// </summary>
        public static string Contabilidadcerradahasta {
            get {
                return ResourceManager.GetString("Contabilidadcerradahasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterio de IVA.
        /// </summary>
        public static string Criterioiva {
            get {
                return ResourceManager.GetString("Criterioiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción corta.
        /// </summary>
        public static string Descripcioncorta {
            get {
                return ResourceManager.GetString("Descripcioncorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string Desde {
            get {
                return ResourceManager.GetString("Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abierto.
        /// </summary>
        public static string EstadoEjercicioAbierto {
            get {
                return ResourceManager.GetString("EstadoEjercicioAbierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrado.
        /// </summary>
        public static string EstadoEjercicioCerrado {
            get {
                return ResourceManager.GetString("EstadoEjercicioCerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejercicio anterior.
        /// </summary>
        public static string Fkejercicios {
            get {
                return ResourceManager.GetString("Fkejercicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie contable.
        /// </summary>
        public static string FkseriescontablesAST {
            get {
                return ResourceManager.GetString("FkseriescontablesAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartera cobros.
        /// </summary>
        public static string FkseriescontablesCRC {
            get {
                return ResourceManager.GetString("FkseriescontablesCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartera pagos.
        /// </summary>
        public static string FkseriescontablesCRP {
            get {
                return ResourceManager.GetString("FkseriescontablesCRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inmovilizado.
        /// </summary>
        public static string FkseriescontablesINM {
            get {
                return ResourceManager.GetString("FkseriescontablesINM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iva repercutido.
        /// </summary>
        public static string FkseriescontablesIVP {
            get {
                return ResourceManager.GetString("FkseriescontablesIVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iva soportado.
        /// </summary>
        public static string FkseriescontablesIVS {
            get {
                return ResourceManager.GetString("FkseriescontablesIVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsión cobros.
        /// </summary>
        public static string FkseriescontablesPRC {
            get {
                return ResourceManager.GetString("FkseriescontablesPRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsión pagos.
        /// </summary>
        public static string FkseriescontablesPRP {
            get {
                return ResourceManager.GetString("FkseriescontablesPRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión remesas.
        /// </summary>
        public static string FkseriescontablesREM {
            get {
                return ResourceManager.GetString("FkseriescontablesREM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión.
        /// </summary>
        public static string Gestion {
            get {
                return ResourceManager.GetString("Gestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string Hasta {
            get {
                return ResourceManager.GetString("Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA cerrado hasta.
        /// </summary>
        public static string Registroivacerradohasta {
            get {
                return ResourceManager.GetString("Registroivacerradohasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejercicios.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
