//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Estados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Estados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Estados", typeof(Estados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albarán de compra.
        /// </summary>
        public static string EnumAlbaranesCompras {
            get {
                return ResourceManager.GetString("EnumAlbaranesCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albarán de venta.
        /// </summary>
        public static string EnumAlbaranesVentas {
            get {
                return ResourceManager.GetString("EnumAlbaranesVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulado.
        /// </summary>
        public static string EnumAnulado {
            get {
                return ResourceManager.GetString("EnumAnulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automático.
        /// </summary>
        public static string EnumAutomatico {
            get {
                return ResourceManager.GetString("EnumAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caducado.
        /// </summary>
        public static string EnumCaducado {
            get {
                return ResourceManager.GetString("EnumCaducado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaña.
        /// </summary>
        public static string EnumCampañas {
            get {
                return ResourceManager.GetString("EnumCampañas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortabloque.
        /// </summary>
        public static string EnumCortabloques {
            get {
                return ResourceManager.GetString("EnumCortabloques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En curso.
        /// </summary>
        public static string EnumCurso {
            get {
                return ResourceManager.GetString("EnumCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En diseño.
        /// </summary>
        public static string EnumDiseno {
            get {
                return ResourceManager.GetString("EnumDiseno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura de compra.
        /// </summary>
        public static string EnumFacturasCompras {
            get {
                return ResourceManager.GetString("EnumFacturasCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura de venta.
        /// </summary>
        public static string EnumFacturasVentas {
            get {
                return ResourceManager.GetString("EnumFacturasVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado.
        /// </summary>
        public static string EnumFinalizado {
            get {
                return ResourceManager.GetString("EnumFinalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidencia.
        /// </summary>
        public static string EnumIncidencias {
            get {
                return ResourceManager.GetString("EnumIncidencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventario.
        /// </summary>
        public static string EnumInventarios {
            get {
                return ResourceManager.GetString("EnumInventarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit.
        /// </summary>
        public static string EnumKits {
            get {
                return ResourceManager.GetString("EnumKits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string EnumManual {
            get {
                return ResourceManager.GetString("EnumManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oportunidad.
        /// </summary>
        public static string EnumOportunidades {
            get {
                return ResourceManager.GetString("EnumOportunidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido de compra.
        /// </summary>
        public static string EnumPedidosCompras {
            get {
                return ResourceManager.GetString("EnumPedidosCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido de venta.
        /// </summary>
        public static string EnumPedidosVentas {
            get {
                return ResourceManager.GetString("EnumPedidosVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto de compra.
        /// </summary>
        public static string EnumPresupuestosCompras {
            get {
                return ResourceManager.GetString("EnumPresupuestosCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto de venta.
        /// </summary>
        public static string EnumPresupuestosVentas {
            get {
                return ResourceManager.GetString("EnumPresupuestosVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto.
        /// </summary>
        public static string EnumProyectos {
            get {
                return ResourceManager.GetString("EnumProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva.
        /// </summary>
        public static string EnumReservas {
            get {
                return ResourceManager.GetString("EnumReservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los documentos.
        /// </summary>
        public static string EnumTodos {
            get {
                return ResourceManager.GetString("EnumTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformación.
        /// </summary>
        public static string EnumTransformaciones {
            get {
                return ResourceManager.GetString("EnumTransformaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformación de acabado.
        /// </summary>
        public static string EnumTransformacioneslotes {
            get {
                return ResourceManager.GetString("EnumTransformacioneslotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traspasos de almacén.
        /// </summary>
        public static string EnumTraspasosalmacen {
            get {
                return ResourceManager.GetString("EnumTraspasosalmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imputa riesgo.
        /// </summary>
        public static string Imputariesgo {
            get {
                return ResourceManager.GetString("Imputariesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permite editar el documento.
        /// </summary>
        public static string LblNoPermiteEditar {
            get {
                return ResourceManager.GetString("LblNoPermiteEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite editar el documento.
        /// </summary>
        public static string LblPermiteEditar {
            get {
                return ResourceManager.GetString("LblPermiteEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Notas {
            get {
                return ResourceManager.GetString("Notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedades del estado.
        /// </summary>
        public static string Tipoestado {
            get {
                return ResourceManager.GetString("Tipoestado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de gestión.
        /// </summary>
        public static string Tipomovimiento {
            get {
                return ResourceManager.GetString("Tipomovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estados.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string TituloEntidadSingular {
            get {
                return ResourceManager.GetString("TituloEntidadSingular", resourceCulture);
            }
        }
    }
}
