//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListadoAcomuladoPeriodos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListadoAcomuladoPeriodos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.ListadoAcomuladoPeriodos", typeof(ListadoAcomuladoPeriodos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excluir documento de Cierre de ejercicio.
        /// </summary>
        public static string CierreEjercicio {
            get {
                return ResourceManager.GetString("CierreEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excluir documento de apertura de ejercicio.
        /// </summary>
        public static string Ejercicio {
            get {
                return ResourceManager.GetString("Ejercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excluir asientos Vinculados.
        /// </summary>
        public static string ExcluirAsientosSimulacion {
            get {
                return ResourceManager.GetString("ExcluirAsientosSimulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excluir docs. De Regularización de existencias.
        /// </summary>
        public static string Existencia {
            get {
                return ResourceManager.GetString("Existencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde Fecha.
        /// </summary>
        public static string FechaDesde {
            get {
                return ResourceManager.GetString("FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta Fecha.
        /// </summary>
        public static string FechaHasta {
            get {
                return ResourceManager.GetString("FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excluir docs. De Regularización Grupos 6 y 7.
        /// </summary>
        public static string Grupos {
            get {
                return ResourceManager.GetString("Grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir ajuste de existencias del periodo.
        /// </summary>
        public static string IncluirAjusteExistenciaPeriodo {
            get {
                return ResourceManager.GetString("IncluirAjusteExistenciaPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir Asientos de Simulación.
        /// </summary>
        public static string IncluirAsientosSimulacion {
            get {
                return ResourceManager.GetString("IncluirAsientosSimulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incluir prorrateo de amortizaciones.
        /// </summary>
        public static string IncluirProrrateoAmortizaciones {
            get {
                return ResourceManager.GetString("IncluirProrrateoAmortizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde Sección.
        /// </summary>
        public static string SeccionDesde {
            get {
                return ResourceManager.GetString("SeccionDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta Sección.
        /// </summary>
        public static string SeccionHasta {
            get {
                return ResourceManager.GetString("SeccionHasta", resourceCulture);
            }
        }
    }
}
