//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Movimientosalmacen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Movimientosalmacen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Movimientosalmacen", typeof(Movimientosalmacen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de zona.
        /// </summary>
        public static string CambioUbicacion {
            get {
                return ResourceManager.GetString("CambioUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobar lote.
        /// </summary>
        public static string Comprobarlote {
            get {
                return ResourceManager.GetString("Comprobarlote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacén.
        /// </summary>
        public static string Fkalmacen {
            get {
                return ResourceManager.GetString("Fkalmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva zona.
        /// </summary>
        public static string Fkzonaalmacen {
            get {
                return ResourceManager.GetString("Fkzonaalmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote.
        /// </summary>
        public static string Lote {
            get {
                return ResourceManager.GetString("Lote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado el cambio de zona correctamente.
        /// </summary>
        public static string MovimientoRealizadoCorrectamente {
            get {
                return ResourceManager.GetString("MovimientoRealizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar zona.
        /// </summary>
        public static string RealizarCambioUbicacion {
            get {
                return ResourceManager.GetString("RealizarCambioUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona actual.
        /// </summary>
        public static string Zonaactual {
            get {
                return ResourceManager.GetString("Zonaactual", resourceCulture);
            }
        }
    }
}
