//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Movs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Movs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Movs", typeof(Movs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string Bloqueado {
            get {
                return ResourceManager.GetString("Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal contable.
        /// </summary>
        public static string Canalcontable {
            get {
                return ResourceManager.GetString("Canalcontable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod. Comentario.
        /// </summary>
        public static string Codigocomentario {
            get {
                return ResourceManager.GetString("Codigocomentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo descripción.
        /// </summary>
        public static string Codigodescripcionasiento {
            get {
                return ResourceManager.GetString("Codigodescripcionasiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string Comentario {
            get {
                return ResourceManager.GetString("Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliado.
        /// </summary>
        public static string Conciliado {
            get {
                return ResourceManager.GetString("Conciliado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde cuenta.
        /// </summary>
        public static string CuentaDesde {
            get {
                return ResourceManager.GetString("CuentaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta cuenta.
        /// </summary>
        public static string CuentaHasta {
            get {
                return ResourceManager.GetString("CuentaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe.
        /// </summary>
        public static string Debe {
            get {
                return ResourceManager.GetString("Debe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción asiento.
        /// </summary>
        public static string Descripcionasiento {
            get {
                return ResourceManager.GetString("Descripcionasiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde documento.
        /// </summary>
        public static string DocumentoDesde {
            get {
                return ResourceManager.GetString("DocumentoDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta documento.
        /// </summary>
        public static string DocumentoHasta {
            get {
                return ResourceManager.GetString("DocumentoHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo importes Debe/Haber descuadrado.
        /// </summary>
        public static string ErrorDescuadreDebeHaber {
            get {
                return ResourceManager.GetString("ErrorDescuadreDebeHaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha del documento no corresponde con la fecha del ejercicio del documento.
        /// </summary>
        public static string ErrorFechaEjercicio {
            get {
                return ResourceManager.GetString("ErrorFechaEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltan dígitos en la cuenta.
        /// </summary>
        public static string ErrorLongitudCuenta {
            get {
                return ResourceManager.GetString("ErrorLongitudCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es debe.
        /// </summary>
        public static string Esdebe {
            get {
                return ResourceManager.GetString("Esdebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde fecha.
        /// </summary>
        public static string FechaDesde {
            get {
                return ResourceManager.GetString("FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta fecha.
        /// </summary>
        public static string FechaHasta {
            get {
                return ResourceManager.GetString("FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha informe.
        /// </summary>
        public static string FechaInforme {
            get {
                return ResourceManager.GetString("FechaInforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string Fkcuentas {
            get {
                return ResourceManager.GetString("Fkcuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejercicio.
        /// </summary>
        public static string Fkejercicio {
            get {
                return ResourceManager.GetString("Fkejercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string Fkmonedas {
            get {
                return ResourceManager.GetString("Fkmonedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección analítica.
        /// </summary>
        public static string Fkseccionesanaliticas {
            get {
                return ResourceManager.GetString("Fkseccionesanaliticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string Fkseriescontables {
            get {
                return ResourceManager.GetString("Fkseriescontables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber.
        /// </summary>
        public static string Haber {
            get {
                return ResourceManager.GetString("Haber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Identificadorsegmento {
            get {
                return ResourceManager.GetString("Identificadorsegmento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        public static string Importe {
            get {
                return ResourceManager.GetString("Importe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe moneda documento.
        /// </summary>
        public static string Importemonedadocumento {
            get {
                return ResourceManager.GetString("Importemonedadocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostras cuentas sin movimientos.
        /// </summary>
        public static string MostrarCuentasSinMovimientos {
            get {
                return ResourceManager.GetString("MostrarCuentasSinMovimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar cuentas sin saldo.
        /// </summary>
        public static string MostrarCuentasSinSaldo {
            get {
                return ResourceManager.GetString("MostrarCuentasSinSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        public static string Orden {
            get {
                return ResourceManager.GetString("Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por grupos.
        /// </summary>
        public static string PorGrupos {
            get {
                return ResourceManager.GetString("PorGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por mayor.
        /// </summary>
        public static string PorMayor {
            get {
                return ResourceManager.GetString("PorMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por nivel 5.
        /// </summary>
        public static string PorNivelCinco {
            get {
                return ResourceManager.GetString("PorNivelCinco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por subcuenta.
        /// </summary>
        public static string PorSubcuenta {
            get {
                return ResourceManager.GetString("PorSubcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por subgrupos.
        /// </summary>
        public static string PorSubgrupos {
            get {
                return ResourceManager.GetString("PorSubgrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por submayor.
        /// </summary>
        public static string PorSubmayor {
            get {
                return ResourceManager.GetString("PorSubmayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencia.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencia del usuario.
        /// </summary>
        public static string ReferenciaLibre {
            get {
                return ResourceManager.GetString("ReferenciaLibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldos anteriores.
        /// </summary>
        public static string SaldosAnteriores {
            get {
                return ResourceManager.GetString("SaldosAnteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma anterior debe.
        /// </summary>
        public static string SumaAnteriorDebe {
            get {
                return ResourceManager.GetString("SumaAnteriorDebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma anterior haber.
        /// </summary>
        public static string SumaAnteriorHaber {
            get {
                return ResourceManager.GetString("SumaAnteriorHaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de asiento.
        /// </summary>
        public static string TipoAsiento {
            get {
                return ResourceManager.GetString("TipoAsiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apertura.
        /// </summary>
        public static string TipoAsientoApertura {
            get {
                return ResourceManager.GetString("TipoAsientoApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apertura provisional.
        /// </summary>
        public static string TipoAsientoAperturaProvisional {
            get {
                return ResourceManager.GetString("TipoAsientoAperturaProvisional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre.
        /// </summary>
        public static string TipoAsientoCierre {
            get {
                return ResourceManager.GetString("TipoAsientoCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TipoAsientoNormal {
            get {
                return ResourceManager.GetString("TipoAsientoNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regularización de existencias.
        /// </summary>
        public static string TipoAsientoRegularizacionExistencias {
            get {
                return ResourceManager.GetString("TipoAsientoRegularizacionExistencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regularización grupos 6 y 7.
        /// </summary>
        public static string TipoAsientoRegularizacionGrupos6y7 {
            get {
                return ResourceManager.GetString("TipoAsientoRegularizacionGrupos6y7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulación.
        /// </summary>
        public static string TipoAsientoSimulacion {
            get {
                return ResourceManager.GetString("TipoAsientoSimulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinculado.
        /// </summary>
        public static string TipoAsientoVinculado {
            get {
                return ResourceManager.GetString("TipoAsientoVinculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de cambio.
        /// </summary>
        public static string Tipocambio {
            get {
                return ResourceManager.GetString("Tipocambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string TipoDocumento {
            get {
                return ResourceManager.GetString("TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimientos Contables.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MovimientoContable.
        /// </summary>
        public static string TituloEntidadSingular {
            get {
                return ResourceManager.GetString("TituloEntidadSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traza.
        /// </summary>
        public static string Traza {
            get {
                return ResourceManager.GetString("Traza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vínculo.
        /// </summary>
        public static string Vinculo {
            get {
                return ResourceManager.GetString("Vinculo", resourceCulture);
            }
        }
    }
}
