//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Prospectos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prospectos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Prospectos", typeof(Prospectos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación.
        /// </summary>
        public static string Clasificacion {
            get {
                return ResourceManager.GetString("Clasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercial.
        /// </summary>
        public static string Comercial {
            get {
                return ResourceManager.GetString("Comercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir Prospecto en Cliente.
        /// </summary>
        public static string ConvertirProspectoCliente {
            get {
                return ResourceManager.GetString("ConvertirProspectoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede crear un Pedido de venta con un Prospecto.
        /// </summary>
        public static string ErrorCrearPedidoProspecto {
            get {
                return ResourceManager.GetString("ErrorCrearPedidoProspecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de contacto.
        /// </summary>
        public static string Fkmodocontacto {
            get {
                return ResourceManager.GetString("Fkmodocontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha definido un Tipo de cuenta para los prospectos..
        /// </summary>
        public static string LblMensajeTipoCuenta {
            get {
                return ResourceManager.GetString("LblMensajeTipoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospectos.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospecto.
        /// </summary>
        public static string TituloEntidadSingular {
            get {
                return ResourceManager.GetString("TituloEntidadSingular", resourceCulture);
            }
        }
    }
}
