//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Seguimientos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Seguimientos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Seguimientos", typeof(Seguimientos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string Accion {
            get {
                return ResourceManager.GetString("Accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        public static string Asunto {
            get {
                return ResourceManager.GetString("Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrado.
        /// </summary>
        public static string Cerrado {
            get {
                return ResourceManager.GetString("Cerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave coste.
        /// </summary>
        public static string Clavecoste {
            get {
                return ResourceManager.GetString("Clavecoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coste.
        /// </summary>
        public static string Coste {
            get {
                return ResourceManager.GetString("Coste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercero.
        /// </summary>
        public static string Descripciontercero {
            get {
                return ResourceManager.GetString("Descripciontercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento relacionado.
        /// </summary>
        public static string Documentorelacionado {
            get {
                return ResourceManager.GetString("Documentorelacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa.
        /// </summary>
        public static string Etapa {
            get {
                return ResourceManager.GetString("Etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fechadocumento {
            get {
                return ResourceManager.GetString("Fechadocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha próximo seguimiento.
        /// </summary>
        public static string Fechaproximoseguimiento {
            get {
                return ResourceManager.GetString("Fechaproximoseguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha resolución.
        /// </summary>
        public static string Fecharesolucion {
            get {
                return ResourceManager.GetString("Fecharesolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión.
        /// </summary>
        public static string Gestion {
            get {
                return ResourceManager.GetString("Gestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar documento relacionado.
        /// </summary>
        public static string LblBuscarDocumentoRelacionado {
            get {
                return ResourceManager.GetString("LblBuscarDocumentoRelacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margen decisión.
        /// </summary>
        public static string Margen {
            get {
                return ResourceManager.GetString("Margen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        public static string Notas {
            get {
                return ResourceManager.GetString("Notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operario.
        /// </summary>
        public static string Operario {
            get {
                return ResourceManager.GetString("Operario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        public static string Origen {
            get {
                return ResourceManager.GetString("Origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reacción.
        /// </summary>
        public static string Reaccion {
            get {
                return ResourceManager.GetString("Reaccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencia.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de doc. relacionado.
        /// </summary>
        public static string Tipodocumentorelacionado {
            get {
                return ResourceManager.GetString("Tipodocumentorelacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimientos.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
