//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SituacionesTesoreria {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SituacionesTesoreria() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.SituacionesTesoreria", typeof(SituacionesTesoreria).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambos.
        /// </summary>
        public static string Ambos {
            get {
                return ResourceManager.GetString("Ambos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Blanco {
            get {
                return ResourceManager.GetString("Blanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobros.
        /// </summary>
        public static string Cobros {
            get {
                return ResourceManager.GetString("Cobros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion2 {
            get {
                return ResourceManager.GetString("Descripcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable.
        /// </summary>
        public static string Editable {
            get {
                return ResourceManager.GetString("Editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impagado.
        /// </summary>
        public static string Impagado {
            get {
                return ResourceManager.GetString("Impagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicial Cobro.
        /// </summary>
        public static string InicialCobro {
            get {
                return ResourceManager.GetString("InicialCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicial Pago.
        /// </summary>
        public static string InicialPago {
            get {
                return ResourceManager.GetString("InicialPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No regularizado.
        /// </summary>
        public static string Noregularizado {
            get {
                return ResourceManager.GetString("Noregularizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        public static string Pagos {
            get {
                return ResourceManager.GetString("Pagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsión.
        /// </summary>
        public static string Prevision {
            get {
                return ResourceManager.GetString("Prevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regularizado.
        /// </summary>
        public static string Regularizado {
            get {
                return ResourceManager.GetString("Regularizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remesable.
        /// </summary>
        public static string Remesable {
            get {
                return ResourceManager.GetString("Remesable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riesgo.
        /// </summary>
        public static string Riesgo {
            get {
                return ResourceManager.GetString("Riesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situaciones de tesorería.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
