//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tarifas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tarifas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Tarifas", typeof(Tarifas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir en tarifa al crear el artículo.
        /// </summary>
        public static string Asignartarifaalcreararticulos {
            get {
                return ResourceManager.GetString("Asignartarifaalcreararticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coste.
        /// </summary>
        public static string Coste {
            get {
                return ResourceManager.GetString("Coste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento.
        /// </summary>
        public static string Descuento {
            get {
                return ResourceManager.GetString("Descuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la tarifa porque tiene valores asociados.
        /// </summary>
        public static string ErrorLineasExistentes {
            get {
                return ResourceManager.GetString("ErrorLineasExistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod. Artículo.
        /// </summary>
        public static string Fkarticulos {
            get {
                return ResourceManager.GetString("Fkarticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad.
        /// </summary>
        public static string Fkarticuloscodigounidad {
            get {
                return ResourceManager.GetString("Fkarticuloscodigounidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Fkarticulosdescripcion {
            get {
                return ResourceManager.GetString("Fkarticulosdescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string Fkcuentas {
            get {
                return ResourceManager.GetString("Fkcuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string Fkmonedas {
            get {
                return ResourceManager.GetString("Fkmonedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA incluido.
        /// </summary>
        public static string Ivaincluido {
            get {
                return ResourceManager.GetString("Ivaincluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración cálculo de precio.
        /// </summary>
        public static string LblCalculoprecio {
            get {
                return ResourceManager.GetString("LblCalculoprecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmula.
        /// </summary>
        public static string LblFormula {
            get {
                return ResourceManager.GetString("LblFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículos.
        /// </summary>
        public static string Lbllistadotarifas {
            get {
                return ResourceManager.GetString("Lbllistadotarifas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio base.
        /// </summary>
        public static string Precioautomaticobase {
            get {
                return ResourceManager.GetString("Precioautomaticobase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia desde.
        /// </summary>
        public static string Precioautomaticofkfamiliasproductosdesde {
            get {
                return ResourceManager.GetString("Precioautomaticofkfamiliasproductosdesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia hasta.
        /// </summary>
        public static string Precioautomaticofkfamiliasproductoshasta {
            get {
                return ResourceManager.GetString("Precioautomaticofkfamiliasproductoshasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material desde.
        /// </summary>
        public static string Precioautomaticofkmaterialesdesde {
            get {
                return ResourceManager.GetString("Precioautomaticofkmaterialesdesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material hasta.
        /// </summary>
        public static string Precioautomaticofkmaterialeshasta {
            get {
                return ResourceManager.GetString("Precioautomaticofkmaterialeshasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % precio base.
        /// </summary>
        public static string Precioautomaticoporcentajebase {
            get {
                return ResourceManager.GetString("Precioautomaticoporcentajebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante.
        /// </summary>
        public static string Precioautomaticoporcentajefijo {
            get {
                return ResourceManager.GetString("Precioautomaticoporcentajefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio mínimo de venta.
        /// </summary>
        public static string Preciominimoventa {
            get {
                return ResourceManager.GetString("Preciominimoventa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio obligatorio.
        /// </summary>
        public static string Precioobligatorio {
            get {
                return ResourceManager.GetString("Precioobligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimiento.
        /// </summary>
        public static string Tipoflujo {
            get {
                return ResourceManager.GetString("Tipoflujo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra.
        /// </summary>
        public static string TipoFlujoCompra {
            get {
                return ResourceManager.GetString("TipoFlujoCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta.
        /// </summary>
        public static string TipoFlujoVenta {
            get {
                return ResourceManager.GetString("TipoFlujoVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipotarifa {
            get {
                return ResourceManager.GetString("Tipotarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Específica.
        /// </summary>
        public static string TipoTarifaEspecifica {
            get {
                return ResourceManager.GetString("TipoTarifaEspecifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string TipoTarifaSistema {
            get {
                return ResourceManager.GetString("TipoTarifaSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifas.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa.
        /// </summary>
        public static string TituloEntidadSingular {
            get {
                return ResourceManager.GetString("TituloEntidadSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UM.
        /// </summary>
        public static string Unidades {
            get {
                return ResourceManager.GetString("Unidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válido desde.
        /// </summary>
        public static string Validodesde {
            get {
                return ResourceManager.GetString("Validodesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válido hasta.
        /// </summary>
        public static string Validohasta {
            get {
                return ResourceManager.GetString("Validohasta", resourceCulture);
            }
        }
    }
}
