//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Trabajos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Trabajos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Trabajos", typeof(Trabajos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string Año {
            get {
                return ResourceManager.GetString("Año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aserrado.
        /// </summary>
        public static string Aserrado {
            get {
                return ResourceManager.GetString("Aserrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elaborado.
        /// </summary>
        public static string Elaborado {
            get {
                return ResourceManager.GetString("Elaborado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El año debe ser un número de 4 dígitos.
        /// </summary>
        public static string ErrorFormatoAño {
            get {
                return ResourceManager.GetString("ErrorFormatoAño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo precio debe tener un valor entre 0 y 9,999,999.99.
        /// </summary>
        public static string ErrorPrecio {
            get {
                return ResourceManager.GetString("ErrorPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo capacidad debe tener un valor entre 0 y 9,999.99.
        /// </summary>
        public static string ErrorRangoCapacidad {
            get {
                return ResourceManager.GetString("ErrorRangoCapacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha debe ser un año dentro del rango 2000-2100.
        /// </summary>
        public static string ErrorRangoFecha {
            get {
                return ResourceManager.GetString("ErrorRangoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acabado final.
        /// </summary>
        public static string Fkacabadofinal {
            get {
                return ResourceManager.GetString("Fkacabadofinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acabado inicial.
        /// </summary>
        public static string Fkacabadoinicial {
            get {
                return ResourceManager.GetString("Fkacabadoinicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículo facturable.
        /// </summary>
        public static string Fkarticulofacturable {
            get {
                return ResourceManager.GetString("Fkarticulofacturable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2 Peso.
        /// </summary>
        public static string M2Peso {
            get {
                return ResourceManager.GetString("M2Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2 Real.
        /// </summary>
        public static string M2Real {
            get {
                return ResourceManager.GetString("M2Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.
        /// </summary>
        public static string M3 {
            get {
                return ResourceManager.GetString("M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio referencia.
        /// </summary>
        public static string PrecioReferencia {
            get {
                return ResourceManager.GetString("PrecioReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de imputación.
        /// </summary>
        public static string Tipoimputacion {
            get {
                return ResourceManager.GetString("Tipoimputacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de trabajo.
        /// </summary>
        public static string Tipotrabajo {
            get {
                return ResourceManager.GetString("Tipotrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajos.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo.
        /// </summary>
        public static string TituloEntidadSingular {
            get {
                return ResourceManager.GetString("TituloEntidadSingular", resourceCulture);
            }
        }
    }
}
