//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.Entidades {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Unidades {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Unidades() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.Entidades.Unidades", typeof(Unidades).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad.
        /// </summary>
        public static string Codigounidad {
            get {
                return ResourceManager.GetString("Codigounidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimales total.
        /// </summary>
        public static string Decimalestotales {
            get {
                return ResourceManager.GetString("Decimalestotales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion2 {
            get {
                return ResourceManager.GetString("Descripcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmula.
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto corto.
        /// </summary>
        public static string Textocorto {
            get {
                return ResourceManager.GetString("Textocorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto corto.
        /// </summary>
        public static string Textocorto2 {
            get {
                return ResourceManager.GetString("Textocorto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de movimiento.
        /// </summary>
        public static string Tiposmovimientostock {
            get {
                return ResourceManager.GetString("Tiposmovimientostock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote.
        /// </summary>
        public static string TiposStockLote {
            get {
                return ResourceManager.GetString("TiposStockLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string TiposStockMovimientosCantidad {
            get {
                return ResourceManager.GetString("TiposStockMovimientosCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad y total.
        /// </summary>
        public static string TiposStockMovimientosCantidadYTotal {
            get {
                return ResourceManager.GetString("TiposStockMovimientosCantidadYTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TiposStockMovimientosTotal {
            get {
                return ResourceManager.GetString("TiposStockMovimientosTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitario.
        /// </summary>
        public static string TiposStockUnitario {
            get {
                return ResourceManager.GetString("TiposStockUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de stock.
        /// </summary>
        public static string Tipostock {
            get {
                return ResourceManager.GetString("Tipostock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string TipoStockFormulasCantidad {
            get {
                return ResourceManager.GetString("TipoStockFormulasCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string TipoStockFormulasLinear {
            get {
                return ResourceManager.GetString("TipoStockFormulasLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superficie.
        /// </summary>
        public static string TipoStockFormulasSuperficie {
            get {
                return ResourceManager.GetString("TipoStockFormulasSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TipoStockFormulasTotal {
            get {
                return ResourceManager.GetString("TipoStockFormulasTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumen.
        /// </summary>
        public static string TipoStockFormulasVolumen {
            get {
                return ResourceManager.GetString("TipoStockFormulasVolumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculado.
        /// </summary>
        public static string TipoStockTotalCalculado {
            get {
                return ResourceManager.GetString("TipoStockTotalCalculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editado.
        /// </summary>
        public static string TipoStockTotalEditado {
            get {
                return ResourceManager.GetString("TipoStockTotalEditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de total.
        /// </summary>
        public static string Tipototal {
            get {
                return ResourceManager.GetString("Tipototal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades.
        /// </summary>
        public static string TituloEntidad {
            get {
                return ResourceManager.GetString("TituloEntidad", resourceCulture);
            }
        }
    }
}
