//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.GeneralUI.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupar por.
        /// </summary>
        public static string Agruparpor {
            get {
                return ResourceManager.GetString("Agruparpor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar a cartera.
        /// </summary>
        public static string AsignarCartera {
            get {
                return ResourceManager.GetString("AsignarCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba configuración email.
        /// </summary>
        public static string AsuntoEmailTest {
            get {
                return ResourceManager.GetString("AsuntoEmailTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nueva línea.
        /// </summary>
        public static string BtnAñadirLinea {
            get {
                return ResourceManager.GetString("BtnAñadirLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar líneas.
        /// </summary>
        public static string BtnBuscarLineas {
            get {
                return ResourceManager.GetString("BtnBuscarLineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectar usuario.
        /// </summary>
        public static string BtnDesconectarUsuario {
            get {
                return ResourceManager.GetString("BtnDesconectarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string BtnEntrar {
            get {
                return ResourceManager.GetString("BtnEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string BtnGuardar {
            get {
                return ResourceManager.GetString("BtnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo registro.
        /// </summary>
        public static string BtnNuevoRegistro {
            get {
                return ResourceManager.GetString("BtnNuevoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string BtnVolver {
            get {
                return ResourceManager.GetString("BtnVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant. Albarán.
        /// </summary>
        public static string CantidadAlbaran {
            get {
                return ResourceManager.GetString("CantidadAlbaran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant. Pedida.
        /// </summary>
        public static string CantidadPedida {
            get {
                return ResourceManager.GetString("CantidadPedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant. Pendiente.
        /// </summary>
        public static string CantidadPendiente {
            get {
                return ResourceManager.GetString("CantidadPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurador de documentos: {0}.
        /// </summary>
        public static string ConfiguradorDocumentos {
            get {
                return ResourceManager.GetString("ConfiguradorDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurador de documentos: Cartera.
        /// </summary>
        public static string configurardocumentoscartera {
            get {
                return ResourceManager.GetString("configurardocumentoscartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contabilidad.
        /// </summary>
        public static string Contabilidad {
            get {
                return ResourceManager.GetString("Contabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba realizada a las {0}.
        /// </summary>
        public static string CuerpoEmailTest {
            get {
                return ResourceManager.GetString("CuerpoEmailTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de lotes.
        /// </summary>
        public static string DetalleLotes {
            get {
                return ResourceManager.GetString("DetalleLotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada.
        /// </summary>
        public static string Entrada {
            get {
                return ResourceManager.GetString("Entrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albarán de compra.
        /// </summary>
        public static string EnumAlbaranesCompras {
            get {
                return ResourceManager.GetString("EnumAlbaranesCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albarán de venta.
        /// </summary>
        public static string EnumAlbaranesVentas {
            get {
                return ResourceManager.GetString("EnumAlbaranesVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anulado.
        /// </summary>
        public static string EnumAnulado {
            get {
                return ResourceManager.GetString("EnumAnulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caducado.
        /// </summary>
        public static string EnumCaducado {
            get {
                return ResourceManager.GetString("EnumCaducado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En curso.
        /// </summary>
        public static string EnumCurso {
            get {
                return ResourceManager.GetString("EnumCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En diseño.
        /// </summary>
        public static string EnumDiseno {
            get {
                return ResourceManager.GetString("EnumDiseno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura de compra.
        /// </summary>
        public static string EnumFacturasCompras {
            get {
                return ResourceManager.GetString("EnumFacturasCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura de venta.
        /// </summary>
        public static string EnumFacturasVentas {
            get {
                return ResourceManager.GetString("EnumFacturasVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizado.
        /// </summary>
        public static string EnumFinalizado {
            get {
                return ResourceManager.GetString("EnumFinalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido de compra.
        /// </summary>
        public static string EnumPedidosCompras {
            get {
                return ResourceManager.GetString("EnumPedidosCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido de venta.
        /// </summary>
        public static string EnumPedidosVentas {
            get {
                return ResourceManager.GetString("EnumPedidosVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuesto de compra.
        /// </summary>
        public static string EnumPresupuestosCompras {
            get {
                return ResourceManager.GetString("EnumPresupuestosCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuesto de venta.
        /// </summary>
        public static string EnumPresupuestosVentas {
            get {
                return ResourceManager.GetString("EnumPresupuestosVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los documentos.
        /// </summary>
        public static string EnumTodos {
            get {
                return ResourceManager.GetString("EnumTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede borrar el artículo porque ya ha sido utilizado en algún documento..
        /// </summary>
        public static string ErrorBorradoArticulosUsados {
            get {
                return ResourceManager.GetString("ErrorBorradoArticulosUsados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede borrar la unidade de medida porque ya ha sido utilizada en algún artículo..
        /// </summary>
        public static string ErrorBorradoUnidadesUsadas {
            get {
                return ResourceManager.GetString("ErrorBorradoUnidadesUsadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} no puede ser mayor que el campo {1}.
        /// </summary>
        public static string ErrorCampo1MayorCampo2 {
            get {
                return ResourceManager.GetString("ErrorCampo1MayorCampo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} no puede estar vacío.
        /// </summary>
        public static string ErrorCampoObligatorio {
            get {
                return ResourceManager.GetString("ErrorCampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ups!! parace que no se ha podido clonar el documento.
        /// </summary>
        public static string ErrorClonarGeneral {
            get {
                return ResourceManager.GetString("ErrorClonarGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una cuenta de tipo {0} con el código {1}.
        /// </summary>
        public static string ErrorCuentaExistente {
            get {
                return ResourceManager.GetString("ErrorCuentaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio indicar una Cuenta.
        /// </summary>
        public static string ErrorCuentaObligatoria {
            get {
                return ResourceManager.GetString("ErrorCuentaObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo decimales precios debe estar comprendido entre 0 y 4.
        /// </summary>
        public static string ErrorDecimalesPrecios {
            get {
                return ResourceManager.GetString("ErrorDecimalesPrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delimitador o formato de csv incorrecto.
        /// </summary>
        public static string ErrorDelimitadorFormato {
            get {
                return ResourceManager.GetString("ErrorDelimitadorFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar un documento en estado finalizado.
        /// </summary>
        public static string ErrorDocumentoFinalizado {
            get {
                return ResourceManager.GetString("ErrorDocumentoFinalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento no tiene líneas..
        /// </summary>
        public static string ErrorDocumentoSinLineas {
            get {
                return ResourceManager.GetString("ErrorDocumentoSinLineas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo ean13 debe tener una longitud máxima de 10 dígitos.
        /// </summary>
        public static string ErrorEan13 {
            get {
                return ResourceManager.GetString("ErrorEan13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha no válida.
        /// </summary>
        public static string ErrorFechaNoValida {
            get {
                return ResourceManager.GetString("ErrorFechaNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor sube tu archivo.
        /// </summary>
        public static string ErrorFichero {
            get {
                return ResourceManager.GetString("ErrorFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del campo {0} no es correcto.
        /// </summary>
        public static string ErrorFormatoCampo {
            get {
                return ResourceManager.GetString("ErrorFormatoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este formato de archivo no es compatible.
        /// </summary>
        public static string ErrorFormatoFichero {
            get {
                return ResourceManager.GetString("ErrorFormatoFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ya existe un artículo con el lote: {0}.{1}.
        /// </summary>
        public static string ErrorGenerarMovimientoStock {
            get {
                return ResourceManager.GetString("ErrorGenerarMovimientoStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Id de acreedor {0} no es válido.
        /// </summary>
        public static string ErrorIdAcreedor {
            get {
                return ResourceManager.GetString("ErrorIdAcreedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar el {0} {1} porque ya ha sido modificado por otro usuario .
        /// </summary>
        public static string ErrorIntegridadReferencial {
            get {
                return ResourceManager.GetString("ErrorIntegridadReferencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio indicar al menos una línea cuando se añaden costes adicionales.
        /// </summary>
        public static string ErrorLineasObligatoriasCostes {
            get {
                return ResourceManager.GetString("ErrorLineasObligatoriasCostes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede generar un lote que ya ha sido vendido.
        /// </summary>
        public static string ErrorLoteSinStock {
            get {
                return ResourceManager.GetString("ErrorLoteSinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los documentos en estado {0} no pueden modificarse.
        /// </summary>
        public static string ErrorModificacionNoValidaPorElEstadoActual {
            get {
                return ResourceManager.GetString("ErrorModificacionNoValidaPorElEstadoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar un registro bloqueado.
        /// </summary>
        public static string ErrorModificarRegistroBloqueado {
            get {
                return ResourceManager.GetString("ErrorModificarRegistroBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor de {0}  tiene que estar entre {1} y {2}.
        /// </summary>
        public static string ErrorRangoEntre {
            get {
                return ResourceManager.GetString("ErrorRangoEntre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rango de fechas ya existe.
        /// </summary>
        public static string ErrorRangoExistente {
            get {
                return ResourceManager.GetString("ErrorRangoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un registro con el mismo código.
        /// </summary>
        public static string ErrorRegistroExistente {
            get {
                return ResourceManager.GetString("ErrorRegistroExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado el tipo de cuenta para {0}.
        /// </summary>
        public static string ErrorTipoCuentaConfiguracion {
            get {
                return ResourceManager.GetString("ErrorTipoCuentaConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de cuenta no es correcto.
        /// </summary>
        public static string ErrorTipoCuentaIncorrecto {
            get {
                return ResourceManager.GetString("ErrorTipoCuentaIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor debe ser mayor o igual que {1}.
        /// </summary>
        public static string ErrorValorMinimo {
            get {
                return ResourceManager.GetString("ErrorValorMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fabricación.
        /// </summary>
        public static string Fabricacion {
            get {
                return ResourceManager.GetString("Fabricacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fabricar.
        /// </summary>
        public static string Fabricar {
            get {
                return ResourceManager.GetString("Fabricar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        public static string Filtros {
            get {
                return ResourceManager.GetString("Filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar movimiento.
        /// </summary>
        public static string GenerarMovimiento {
            get {
                return ResourceManager.GetString("GenerarMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ficheros adjuntos.
        /// </summary>
        public static string GestionFicheros {
            get {
                return ResourceManager.GetString("GestionFicheros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imputación materiales.
        /// </summary>
        public static string ImputacionMateriales {
            get {
                return ResourceManager.GetString("ImputacionMateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string LblAceptar {
            get {
                return ResourceManager.GetString("LblAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad.
        /// </summary>
        public static string LblActividad {
            get {
                return ResourceManager.GetString("LblActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador.
        /// </summary>
        public static string LblAdministrador {
            get {
                return ResourceManager.GetString("LblAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupación.
        /// </summary>
        public static string LblAgrupacion {
            get {
                return ResourceManager.GetString("LblAgrupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupado por cliente.
        /// </summary>
        public static string LblAgrupadoporcliente {
            get {
                return ResourceManager.GetString("LblAgrupadoporcliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupado por proveedor.
        /// </summary>
        public static string LblAgrupadoporproveedor {
            get {
                return ResourceManager.GetString("LblAgrupadoporproveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albarán de venta.
        /// </summary>
        public static string LblAlbaranes {
            get {
                return ResourceManager.GetString("LblAlbaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ampliar.
        /// </summary>
        public static string LblAmpliar {
            get {
                return ResourceManager.GetString("LblAmpliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string LblAñadir {
            get {
                return ResourceManager.GetString("LblAñadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string LblAnterior {
            get {
                return ResourceManager.GetString("LblAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aquí.
        /// </summary>
        public static string LblAqui {
            get {
                return ResourceManager.GetString("LblAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articulos tercero.
        /// </summary>
        public static string Lblarticulostercero {
            get {
                return ResourceManager.GetString("Lblarticulostercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asiento.
        /// </summary>
        public static string LblAsiento {
            get {
                return ResourceManager.GetString("LblAsiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención.
        /// </summary>
        public static string LblAtencion {
            get {
                return ResourceManager.GetString("LblAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda online.
        /// </summary>
        public static string LblAyuda {
            get {
                return ResourceManager.GetString("LblAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bancos.
        /// </summary>
        public static string LblBancos {
            get {
                return ResourceManager.GetString("LblBancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bien.
        /// </summary>
        public static string LblBien {
            get {
                return ResourceManager.GetString("LblBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        public static string LblBienvenido {
            get {
                return ResourceManager.GetString("LblBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueada.
        /// </summary>
        public static string LblBloqueada {
            get {
                return ResourceManager.GetString("LblBloqueada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueado.
        /// </summary>
        public static string LblBloqueado {
            get {
                return ResourceManager.GetString("LblBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloquear.
        /// </summary>
        public static string LblBloquear {
            get {
                return ResourceManager.GetString("LblBloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueo.
        /// </summary>
        public static string LblBloqueo {
            get {
                return ResourceManager.GetString("LblBloqueo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está apunto de desbloquear el registro actual, ¿Desea continuar?.
        /// </summary>
        public static string LblBloqueoConfirmacionParte1 {
            get {
                return ResourceManager.GetString("LblBloqueoConfirmacionParte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string LblBorrar {
            get {
                return ResourceManager.GetString("LblBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string LblBuscar {
            get {
                return ResourceManager.GetString("LblBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar componente.
        /// </summary>
        public static string LblBuscarComponente {
            get {
                return ResourceManager.GetString("LblBuscarComponente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsquedas.
        /// </summary>
        public static string LblBusquedas {
            get {
                return ResourceManager.GetString("LblBusquedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contiene cabecera.
        /// </summary>
        public static string LblCabecera {
            get {
                return ResourceManager.GetString("LblCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cajas.
        /// </summary>
        public static string LblCajas {
            get {
                return ResourceManager.GetString("LblCajas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar de almacén.
        /// </summary>
        public static string LblCambiarAlmacen {
            get {
                return ResourceManager.GetString("LblCambiarAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar ejercicio.
        /// </summary>
        public static string LblCambiarEjercicio {
            get {
                return ResourceManager.GetString("LblCambiarEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar de empresa.
        /// </summary>
        public static string LblCambiarEmpresa {
            get {
                return ResourceManager.GetString("LblCambiarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar estado.
        /// </summary>
        public static string LblCambiarEstado {
            get {
                return ResourceManager.GetString("LblCambiarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string LblCancelar {
            get {
                return ResourceManager.GetString("LblCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cartera.
        /// </summary>
        public static string LblCartera {
            get {
                return ResourceManager.GetString("LblCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string LblCerrar {
            get {
                return ResourceManager.GetString("LblCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string LblCerrarSesion {
            get {
                return ResourceManager.GetString("LblCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre.
        /// </summary>
        public static string LblCierre {
            get {
                return ResourceManager.GetString("LblCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clonar.
        /// </summary>
        public static string LblClonar {
            get {
                return ResourceManager.GetString("LblClonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficientes.
        /// </summary>
        public static string LblCoeficientes {
            get {
                return ResourceManager.GetString("LblCoeficientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string LblConfiguracion {
            get {
                return ResourceManager.GetString("LblConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de gráficas.
        /// </summary>
        public static string LblConfigurarGraficas {
            get {
                return ResourceManager.GetString("LblConfigurarGraficas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar panel de control.
        /// </summary>
        public static string LblConfigurarPanelControl {
            get {
                return ResourceManager.GetString("LblConfigurarPanelControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configúrelo desde.
        /// </summary>
        public static string LblConfigureloDesde {
            get {
                return ResourceManager.GetString("LblConfigureloDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar contabilidad.
        /// </summary>
        public static string LblContabilidad {
            get {
                return ResourceManager.GetString("LblContabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contabilizar.
        /// </summary>
        public static string LblContabilizar {
            get {
                return ResourceManager.GetString("LblContabilizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactos.
        /// </summary>
        public static string LblContactos {
            get {
                return ResourceManager.GetString("LblContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string LblContinuar {
            get {
                return ResourceManager.GetString("LblContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correos Enviados.
        /// </summary>
        public static string lblCorreos {
            get {
                return ResourceManager.GetString("lblCorreos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coste del producto.
        /// </summary>
        public static string LblCostesproducto {
            get {
                return ResourceManager.GetString("LblCostesproducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string LblCrear {
            get {
                return ResourceManager.GetString("LblCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas de nivel superior.
        /// </summary>
        public static string LblCuentasNivelSuperior {
            get {
                return ResourceManager.GetString("LblCuentasNivelSuperior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delimitador.
        /// </summary>
        public static string LblDelimitador {
            get {
                return ResourceManager.GetString("LblDelimitador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloqueo de.
        /// </summary>
        public static string LblDesbloqueo {
            get {
                return ResourceManager.GetString("LblDesbloqueo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string LblDescargar {
            get {
                return ResourceManager.GetString("LblDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectar.
        /// </summary>
        public static string LblDesconectar {
            get {
                return ResourceManager.GetString("LblDesconectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string LblDescripcion {
            get {
                return ResourceManager.GetString("LblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desglosado.
        /// </summary>
        public static string LblDesglosado {
            get {
                return ResourceManager.GetString("LblDesglosado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desglose.
        /// </summary>
        public static string LblDesglose {
            get {
                return ResourceManager.GetString("LblDesglose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detallado.
        /// </summary>
        public static string LblDetallado {
            get {
                return ResourceManager.GetString("LblDetallado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diario contable.
        /// </summary>
        public static string LblDiarioContable {
            get {
                return ResourceManager.GetString("LblDiarioContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días.
        /// </summary>
        public static string LblDiferencia {
            get {
                return ResourceManager.GetString("LblDiferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direcciones.
        /// </summary>
        public static string LblDirecciones {
            get {
                return ResourceManager.GetString("LblDirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dividir.
        /// </summary>
        public static string LblDividir {
            get {
                return ResourceManager.GetString("LblDividir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos relacionados.
        /// </summary>
        public static string LblDocumentosrelacionados {
            get {
                return ResourceManager.GetString("LblDocumentosrelacionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string LblEditar {
            get {
                return ResourceManager.GetString("LblEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectivo.
        /// </summary>
        public static string LblEfectivo {
            get {
                return ResourceManager.GetString("LblEfectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de ejercicios.
        /// </summary>
        public static string LblEjercicio {
            get {
                return ResourceManager.GetString("LblEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresas.
        /// </summary>
        public static string LblEmpresas {
            get {
                return ResourceManager.GetString("LblEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar entrega.
        /// </summary>
        public static string LblEntregar {
            get {
                return ResourceManager.GetString("LblEntregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviando email.....
        /// </summary>
        public static string LblEnviandoMail {
            get {
                return ResourceManager.GetString("LblEnviandoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string LblEnviar {
            get {
                return ResourceManager.GetString("LblEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar email.
        /// </summary>
        public static string LblEnviaremail {
            get {
                return ResourceManager.GetString("LblEnviaremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string LblEnvioMail {
            get {
                return ResourceManager.GetString("LblEnvioMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está permitido bloquear esta entidad.
        /// </summary>
        public static string LblErrorBloqueoNoPermitido {
            get {
                return ResourceManager.GetString("LblErrorBloqueoNoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a .
        /// </summary>
        public static string LblExportar {
            get {
                return ResourceManager.GetString("LblExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a Marfil Classic.
        /// </summary>
        public static string LblExportarClassic {
            get {
                return ResourceManager.GetString("LblExportarClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturar.
        /// </summary>
        public static string LblFacturar {
            get {
                return ResourceManager.GetString("LblFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas emitidas.
        /// </summary>
        public static string lblFacturasEmitidas {
            get {
                return ResourceManager.GetString("lblFacturasEmitidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas recibidas.
        /// </summary>
        public static string lblFacturasRecibidas {
            get {
                return ResourceManager.GetString("lblFacturasRecibidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fichero.
        /// </summary>
        public static string LblFichero {
            get {
                return ResourceManager.GetString("LblFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        public static string LblFiltros {
            get {
                return ResourceManager.GetString("LblFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        public static string LblFinalizar {
            get {
                return ResourceManager.GetString("LblFinalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de pago.
        /// </summary>
        public static string LblFormaPago {
            get {
                return ResourceManager.GetString("LblFormaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string LblGeneral {
            get {
                return ResourceManager.GetString("LblGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar albarán.
        /// </summary>
        public static string LblGenerarAlbaran {
            get {
                return ResourceManager.GetString("LblGenerarAlbaran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar cuentas.
        /// </summary>
        public static string LblGenerarCuentas {
            get {
                return ResourceManager.GetString("LblGenerarCuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden de generación de descripción.
        /// </summary>
        public static string LblGenerarDescripcion {
            get {
                return ResourceManager.GetString("LblGenerarDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar diario contable.
        /// </summary>
        public static string LblGenerarDiarioContable {
            get {
                return ResourceManager.GetString("LblGenerarDiarioContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar entrega de stock.
        /// </summary>
        public static string LblGenerarEntrega {
            get {
                return ResourceManager.GetString("LblGenerarEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imputación de materiales.
        /// </summary>
        public static string LblGenerarImputacionMateriales {
            get {
                return ResourceManager.GetString("LblGenerarImputacionMateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar pedido.
        /// </summary>
        public static string LblGenerarPedido {
            get {
                return ResourceManager.GetString("LblGenerarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar recepción de stock.
        /// </summary>
        public static string LblGenerarRecepcionStock {
            get {
                return ResourceManager.GetString("LblGenerarRecepcionStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secciones analíticas.
        /// </summary>
        public static string LblGenerarSecciones {
            get {
                return ResourceManager.GetString("LblGenerarSecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar seguimiento.
        /// </summary>
        public static string LblGenerarSeguimiento {
            get {
                return ResourceManager.GetString("LblGenerarSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión.
        /// </summary>
        public static string LblGestion {
            get {
                return ResourceManager.GetString("LblGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de cambios de monedas.
        /// </summary>
        public static string LblGestionCambioMonedas {
            get {
                return ResourceManager.GetString("LblGestionCambioMonedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de cambios.
        /// </summary>
        public static string LblGestionCambios {
            get {
                return ResourceManager.GetString("LblGestionCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de.
        /// </summary>
        public static string LblGestionDe {
            get {
                return ResourceManager.GetString("LblGestionDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de configuración de gráficas de .
        /// </summary>
        public static string LblGestionDeGraficas {
            get {
                return ResourceManager.GetString("LblGestionDeGraficas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestion de grupos.
        /// </summary>
        public static string LblGestionGrupos {
            get {
                return ResourceManager.GetString("LblGestionGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de usuarios.
        /// </summary>
        public static string LblGestionUsuarios {
            get {
                return ResourceManager.GetString("LblGestionUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear gráfica.
        /// </summary>
        public static string LblGraficas {
            get {
                return ResourceManager.GetString("LblGraficas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string LblGuardar {
            get {
                return ResourceManager.GetString("LblGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Histórico de cambios.
        /// </summary>
        public static string LblHistoricoCambios {
            get {
                return ResourceManager.GetString("LblHistoricoCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Histórico precios.
        /// </summary>
        public static string LblHistoricoPrecios {
            get {
                return ResourceManager.GetString("LblHistoricoPrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LblId {
            get {
                return ResourceManager.GetString("LblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso de importación de líneas.
        /// </summary>
        public static string LblImportar {
            get {
                return ResourceManager.GetString("LblImportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar Artículos.
        /// </summary>
        public static string LblImportarArticulos {
            get {
                return ResourceManager.GetString("LblImportarArticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string LblImportarStock {
            get {
                return ResourceManager.GetString("LblImportarStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        public static string LblImprimir {
            get {
                return ResourceManager.GetString("LblImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indica el motivo por el que quiere bloquear la.
        /// </summary>
        public static string LblIndicaMotivoBloqueo {
            get {
                return ResourceManager.GetString("LblIndicaMotivoBloqueo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información subcuenta.
        /// </summary>
        public static string LblInformacionSubcuenta {
            get {
                return ResourceManager.GetString("LblInformacionSubcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string LblInicio {
            get {
                return ResourceManager.GetString("LblInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código ISO.
        /// </summary>
        public static string LblIso {
            get {
                return ResourceManager.GetString("LblIso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string LblLimpiar {
            get {
                return ResourceManager.GetString("LblLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado.
        /// </summary>
        public static string LblListado {
            get {
                return ResourceManager.GetString("LblListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listar.
        /// </summary>
        public static string LblListar {
            get {
                return ResourceManager.GetString("LblListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        public static string LblLoading {
            get {
                return ResourceManager.GetString("LblLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud total.
        /// </summary>
        public static string LblLongitudTotal {
            get {
                return ResourceManager.GetString("LblLongitudTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandato requerido.
        /// </summary>
        public static string LblMandatoRequerido {
            get {
                return ResourceManager.GetString("LblMandatoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mediación.
        /// </summary>
        public static string LblMediacion {
            get {
                return ResourceManager.GetString("LblMediacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medidas.
        /// </summary>
        public static string LblMedidas {
            get {
                return ResourceManager.GetString("LblMedidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está apunto de eliminar el registro.¿Desea continuar?.
        /// </summary>
        public static string LblMensajeConfirmacionBorrado {
            get {
                return ResourceManager.GetString("LblMensajeConfirmacionBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string LblMenu {
            get {
                return ResourceManager.GetString("LblMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú de administrador.
        /// </summary>
        public static string LblMenuSuperusuario {
            get {
                return ResourceManager.GetString("LblMenuSuperusuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string LblNivel {
            get {
                return ResourceManager.GetString("LblNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloqueada.
        /// </summary>
        public static string LblNoBloqueada {
            get {
                return ResourceManager.GetString("LblNoBloqueada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado una moneda adicional.
        /// </summary>
        public static string LblNoConfiguracionMonedaAdicional {
            get {
                return ResourceManager.GetString("LblNoConfiguracionMonedaAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen bancos asociados.
        /// </summary>
        public static string LblNoExistenBancos {
            get {
                return ResourceManager.GetString("LblNoExistenBancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen cuentas de nivel superior.
        /// </summary>
        public static string LblNoExistenCuentas {
            get {
                return ResourceManager.GetString("LblNoExistenCuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen direcciones.
        /// </summary>
        public static string LblNoExistenDirecciones {
            get {
                return ResourceManager.GetString("LblNoExistenDirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningún almacén.
        /// </summary>
        public static string LblNoExistenMasAlmacenes {
            get {
                return ResourceManager.GetString("LblNoExistenMasAlmacenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay más ejercicios.
        /// </summary>
        public static string LblNoExistenMasEjercicios {
            get {
                return ResourceManager.GetString("LblNoExistenMasEjercicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen más empresas.
        /// </summary>
        public static string LblNoExistenMasEmpresas {
            get {
                return ResourceManager.GetString("LblNoExistenMasEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros.
        /// </summary>
        public static string LblNoHayRegistros {
            get {
                return ResourceManager.GetString("LblNoHayRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string LblNuevo {
            get {
                return ResourceManager.GetString("LblNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operario.
        /// </summary>
        public static string LblOperario {
            get {
                return ResourceManager.GetString("LblOperario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar por.
        /// </summary>
        public static string LblOrdernar {
            get {
                return ResourceManager.GetString("LblOrdernar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros.
        /// </summary>
        public static string LblOtros {
            get {
                return ResourceManager.GetString("LblOtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos de venta.
        /// </summary>
        public static string LblPedidos {
            get {
                return ResourceManager.GetString("LblPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string LblPerfil {
            get {
                return ResourceManager.GetString("LblPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        public static string LblPersonalizado {
            get {
                return ResourceManager.GetString("LblPersonalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peticiones asíncronas.
        /// </summary>
        public static string LblPeticionesAsincronas {
            get {
                return ResourceManager.GetString("LblPeticionesAsincronas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan contable.
        /// </summary>
        public static string LblPlanContable {
            get {
                return ResourceManager.GetString("LblPlanContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje total.
        /// </summary>
        public static string LblPorcentajeTotal {
            get {
                return ResourceManager.GetString("LblPorcentajeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestos de venta.
        /// </summary>
        public static string LblPresupuestos {
            get {
                return ResourceManager.GetString("LblPresupuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previsión.
        /// </summary>
        public static string LblPrevisiones {
            get {
                return ResourceManager.GetString("LblPrevisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primero.
        /// </summary>
        public static string LblPrimero {
            get {
                return ResourceManager.GetString("LblPrimero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producción.
        /// </summary>
        public static string LblProduccion {
            get {
                return ResourceManager.GetString("LblProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades.
        /// </summary>
        public static string LblPropiedades {
            get {
                return ResourceManager.GetString("LblPropiedades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar seleccionados.
        /// </summary>
        public static string LblQuitarSeleccionados {
            get {
                return ResourceManager.GetString("LblQuitarSeleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón social.
        /// </summary>
        public static string LblRazonSocial {
            get {
                return ResourceManager.GetString("LblRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Régimen especial.
        /// </summary>
        public static string LblRegimenEspecial {
            get {
                return ResourceManager.GetString("LblRegimenEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remesable.
        /// </summary>
        public static string LblRemesable {
            get {
                return ResourceManager.GetString("LblRemesable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saldar pedido.
        /// </summary>
        public static string LblSaldarPedido {
            get {
                return ResourceManager.GetString("LblSaldarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        public static string LblSeguridad {
            get {
                return ResourceManager.GetString("LblSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie.
        /// </summary>
        public static string LblSerie {
            get {
                return ResourceManager.GetString("LblSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios.
        /// </summary>
        public static string LblServicios {
            get {
                return ResourceManager.GetString("LblServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string LblSettings {
            get {
                return ResourceManager.GetString("LblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string LblSiguiente {
            get {
                return ResourceManager.GetString("LblSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Desglosar.
        /// </summary>
        public static string LblSinDesglose {
            get {
                return ResourceManager.GetString("LblSinDesglose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifas de compra.
        /// </summary>
        public static string LblTarifasCompras {
            get {
                return ResourceManager.GetString("LblTarifasCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifa específica de compra.
        /// </summary>
        public static string LblTarifasEspecificasCompras {
            get {
                return ResourceManager.GetString("LblTarifasEspecificasCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifa específica de venta.
        /// </summary>
        public static string LblTarifasEspecificasVentas {
            get {
                return ResourceManager.GetString("LblTarifasEspecificasVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifas de venta.
        /// </summary>
        public static string LblTarifasVentas {
            get {
                return ResourceManager.GetString("LblTarifasVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terceros.
        /// </summary>
        public static string Lbltercero {
            get {
                return ResourceManager.GetString("Lbltercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0} ya está en uso. Desea forzar la desconexión del usuario?.
        /// </summary>
        public static string LblTextoDesconexion {
            get {
                return ResourceManager.GetString("LblTextoDesconexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo lote.
        /// </summary>
        public static string LblTipoAlmacenLote {
            get {
                return ResourceManager.GetString("LblTipoAlmacenLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de factura.
        /// </summary>
        public static string LblTipoFactura {
            get {
                return ResourceManager.GetString("LblTipoFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transporte.
        /// </summary>
        public static string LblTransporte {
            get {
                return ResourceManager.GetString("LblTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última modificación.
        /// </summary>
        public static string LblUltimaModificacion {
            get {
                return ResourceManager.GetString("LblUltimaModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Último.
        /// </summary>
        public static string LblUltimo {
            get {
                return ResourceManager.GetString("LblUltimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Últimos precios.
        /// </summary>
        public static string LblUltimosPrecios {
            get {
                return ResourceManager.GetString("LblUltimosPrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades de medida.
        /// </summary>
        public static string LblUnidades {
            get {
                return ResourceManager.GetString("LblUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string LblUsuarios {
            get {
                return ResourceManager.GetString("LblUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validaciones.
        /// </summary>
        public static string LblValidar {
            get {
                return ResourceManager.GetString("LblValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variedades/Tajos.
        /// </summary>
        public static string LblVariedades {
            get {
                return ResourceManager.GetString("LblVariedades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vencimientos.
        /// </summary>
        public static string LblVencimientos {
            get {
                return ResourceManager.GetString("LblVencimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguimientos.
        /// </summary>
        public static string LblVencimientosSeguimientos {
            get {
                return ResourceManager.GetString("LblVencimientosSeguimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string LblVer {
            get {
                return ResourceManager.GetString("LblVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a la lista.
        /// </summary>
        public static string LblVolverALaLista {
            get {
                return ResourceManager.GetString("LblVolverALaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de control de lotes.
        /// </summary>
        public static string Lotes {
            get {
                return ResourceManager.GetString("Lotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha clonado el registro correctamente.
        /// </summary>
        public static string MensajeExitoClonar {
            get {
                return ResourceManager.GetString("MensajeExitoClonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación se ha realizado correctamente.
        /// </summary>
        public static string MensajeExitoOperacion {
            get {
                return ResourceManager.GetString("MensajeExitoOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha desconectado al otro usuario correctamente. Ya puede intentar conectarse a la aplicación..
        /// </summary>
        public static string MensajeExitoOperacionForzarDesconexion {
            get {
                return ResourceManager.GetString("MensajeExitoOperacionForzarDesconexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metros Albarán.
        /// </summary>
        public static string MetrosAlbaran {
            get {
                return ResourceManager.GetString("MetrosAlbaran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimientos de tesorería.
        /// </summary>
        public static string MovimientosTesoreria {
            get {
                return ResourceManager.GetString("MovimientosTesoreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestar.
        /// </summary>
        public static string Presupuestar {
            get {
                return ResourceManager.GetString("Presupuestar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Produccion.
        /// </summary>
        public static string Produccion {
            get {
                return ResourceManager.GetString("Produccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida.
        /// </summary>
        public static string Salida {
            get {
                return ResourceManager.GetString("Salida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin agrupar.
        /// </summary>
        public static string Sinagrupar {
            get {
                return ResourceManager.GetString("Sinagrupar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock actual.
        /// </summary>
        public static string StockActual {
            get {
                return ResourceManager.GetString("StockActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir imagen.
        /// </summary>
        public static string SubirImagen {
            get {
                return ResourceManager.GetString("SubirImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string TipoOperacionServiceActualizar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bundle.
        /// </summary>
        public static string TipoOperacionServiceBundle {
            get {
                return ResourceManager.GetString("TipoOperacionServiceBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string TipoOperacionServiceEliminar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar.
        /// </summary>
        public static string TipoOperacionServiceInsertar {
            get {
                return ResourceManager.GetString("TipoOperacionServiceInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kit.
        /// </summary>
        public static string TipoOperacionServiceKit {
            get {
                return ResourceManager.GetString("TipoOperacionServiceKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimiento de almacén.
        /// </summary>
        public static string TipoOperacionServiceMovimientoAlmacen {
            get {
                return ResourceManager.GetString("TipoOperacionServiceMovimientoAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remedir.
        /// </summary>
        public static string TipoOperacionServiceRemedir {
            get {
                return ResourceManager.GetString("TipoOperacionServiceRemedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades.
        /// </summary>
        public static string Unidades {
            get {
                return ResourceManager.GetString("Unidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de previsión de cobros.
        /// </summary>
        public static string VencimientosCobros {
            get {
                return ResourceManager.GetString("VencimientosCobros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de previsión de pagos.
        /// </summary>
        public static string VencimientosPagos {
            get {
                return ResourceManager.GetString("VencimientosPagos", resourceCulture);
            }
        }
    }
}
