//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.GeneralUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TiposDocumentosContables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TiposDocumentosContables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.GeneralUI.TiposDocumentosContables", typeof(TiposDocumentosContables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apertura.
        /// </summary>
        public static string EnumApertura {
            get {
                return ResourceManager.GetString("EnumApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apertura provisional.
        /// </summary>
        public static string EnumAperturaProvisional {
            get {
                return ResourceManager.GetString("EnumAperturaProvisional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diario.
        /// </summary>
        public static string EnumAsientos {
            get {
                return ResourceManager.GetString("EnumAsientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asiento vinculado.
        /// </summary>
        public static string EnumAsientoVinculado {
            get {
                return ResourceManager.GetString("EnumAsientoVinculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre.
        /// </summary>
        public static string EnumCierre {
            get {
                return ResourceManager.GetString("EnumCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string EnumNormal {
            get {
                return ResourceManager.GetString("EnumNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regularización de existencias.
        /// </summary>
        public static string EnumRegularizacionExistencias {
            get {
                return ResourceManager.GetString("EnumRegularizacionExistencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regularización de grupos 6 y 7.
        /// </summary>
        public static string EnumRegularizacionGrupos6y7 {
            get {
                return ResourceManager.GetString("EnumRegularizacionGrupos6y7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulación.
        /// </summary>
        public static string EnumSimulacion {
            get {
                return ResourceManager.GetString("EnumSimulacion", resourceCulture);
            }
        }
    }
}
