//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marfil.Inf.ResourcesGlobalization.Textos.MenuAplicacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menuaplicacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menuaplicacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marfil.Inf.ResourcesGlobalization.Textos.MenuAplicacion.Menuaplicacion", typeof(Menuaplicacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acabados.
        /// </summary>
        public static string acabados {
            get {
                return ResourceManager.GetString("acabados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acreedores.
        /// </summary>
        public static string acreedores {
            get {
                return ResourceManager.GetString("acreedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agentes.
        /// </summary>
        public static string agentes {
            get {
                return ResourceManager.GetString("agentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de albaranes de taller.
        /// </summary>
        public static string albaranes {
            get {
                return ResourceManager.GetString("albaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albaranes de taller.
        /// </summary>
        public static string albaranescompras {
            get {
                return ResourceManager.GetString("albaranescompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de devoluciones.
        /// </summary>
        public static string albaranesdevolucion {
            get {
                return ResourceManager.GetString("albaranesdevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de almacenes.
        /// </summary>
        public static string almacen {
            get {
                return ResourceManager.GetString("almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículos.
        /// </summary>
        public static string articulos {
            get {
                return ResourceManager.GetString("articulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañías de seguros.
        /// </summary>
        public static string aseguradoras {
            get {
                return ResourceManager.GetString("aseguradoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistente: Generar pedidos de compra.
        /// </summary>
        public static string asistentepedidoscompras {
            get {
                return ResourceManager.GetString("asistentepedidoscompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistente de modificación de lotes.
        /// </summary>
        public static string asistenteremedir {
            get {
                return ResourceManager.GetString("asistenteremedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        public static string ayuda {
            get {
                return ResourceManager.GetString("ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bancos.
        /// </summary>
        public static string bancos {
            get {
                return ResourceManager.GetString("bancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de bundles.
        /// </summary>
        public static string bundle {
            get {
                return ResourceManager.GetString("bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de cambios de monedas.
        /// </summary>
        public static string cambiosmonedas {
            get {
                return ResourceManager.GetString("cambiosmonedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar lote de zona.
        /// </summary>
        public static string cambioubicacion {
            get {
                return ResourceManager.GetString("cambioubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campañas.
        /// </summary>
        public static string campañas {
            get {
                return ResourceManager.GetString("campañas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Características.
        /// </summary>
        public static string caracteristicas {
            get {
                return ResourceManager.GetString("caracteristicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cartera.
        /// </summary>
        public static string carteravencimientos {
            get {
                return ResourceManager.GetString("carteravencimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circuitos de tesorería.
        /// </summary>
        public static string circuitotesoreriacobros {
            get {
                return ResourceManager.GetString("circuitotesoreriacobros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string clientes {
            get {
                return ResourceManager.GetString("clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comerciales.
        /// </summary>
        public static string comerciales {
            get {
                return ResourceManager.GetString("comerciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compras.
        /// </summary>
        public static string compras {
            get {
                return ResourceManager.GetString("compras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string configuracion {
            get {
                return ResourceManager.GetString("configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurador de documentos.
        /// </summary>
        public static string configurardocumentos {
            get {
                return ResourceManager.GetString("configurardocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. Doc. Balance Pedidos.
        /// </summary>
        public static string configurardocumentosbalancepedidos {
            get {
                return ResourceManager.GetString("configurardocumentosbalancepedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. de documentos: Bundles.
        /// </summary>
        public static string configurardocumentosbundle {
            get {
                return ResourceManager.GetString("configurardocumentosbundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. de documentos: Diario.
        /// </summary>
        public static string configurardocumentosdiario {
            get {
                return ResourceManager.GetString("configurardocumentosdiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. de documentos: inventarios.
        /// </summary>
        public static string configurardocumentosinventarios {
            get {
                return ResourceManager.GetString("configurardocumentosinventarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. de documentos: Kits.
        /// </summary>
        public static string configurardocumentoskit {
            get {
                return ResourceManager.GetString("configurardocumentoskit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. Docum. Margen.
        /// </summary>
        public static string configurardocumentoslistadomargen {
            get {
                return ResourceManager.GetString("configurardocumentoslistadomargen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. de documentos: Mayor.
        /// </summary>
        public static string configurardocumentosmayor {
            get {
                return ResourceManager.GetString("configurardocumentosmayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. de documentos: pedidos.
        /// </summary>
        public static string configurardocumentospedidos {
            get {
                return ResourceManager.GetString("configurardocumentospedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. de documentos: reservas.
        /// </summary>
        public static string configurardocumentosreservas {
            get {
                return ResourceManager.GetString("configurardocumentosreservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. de docs: Sumas y Saldos.
        /// </summary>
        public static string configurardocumentossumas {
            get {
                return ResourceManager.GetString("configurardocumentossumas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. de docs: transformaciones.
        /// </summary>
        public static string configurardocumentostransformaciones {
            get {
                return ResourceManager.GetString("configurardocumentostransformaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. de documentos: traspasos.
        /// </summary>
        public static string configurardocumentostraspasos {
            get {
                return ResourceManager.GetString("configurardocumentostraspasos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Visual.
        /// </summary>
        public static string consultavisual {
            get {
                return ResourceManager.GetString("consultavisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contabilidad.
        /// </summary>
        public static string contabilidad {
            get {
                return ResourceManager.GetString("contabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contadores de documentos.
        /// </summary>
        public static string contadores {
            get {
                return ResourceManager.GetString("contadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costes Variables Periodo.
        /// </summary>
        public static string costesvariablesperiodo {
            get {
                return ResourceManager.GetString("costesvariablesperiodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterios de agrupación.
        /// </summary>
        public static string criteriosagrupacion {
            get {
                return ResourceManager.GetString("criteriosagrupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRM.
        /// </summary>
        public static string CRM {
            get {
                return ResourceManager.GetString("CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas.
        /// </summary>
        public static string cuentas {
            get {
                return ResourceManager.GetString("cuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas de tesorería.
        /// </summary>
        public static string cuentastesoreria {
            get {
                return ResourceManager.GetString("cuentastesoreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diario de stock.
        /// </summary>
        public static string diariostock {
            get {
                return ResourceManager.GetString("diariostock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de división de lotes.
        /// </summary>
        public static string divisionlotes {
            get {
                return ResourceManager.GetString("divisionlotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entradas varias.
        /// </summary>
        public static string entradasvarias {
            get {
                return ResourceManager.GetString("entradasvarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de entregas de stock.
        /// </summary>
        public static string entregasstock {
            get {
                return ResourceManager.GetString("entregasstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estados de documentos.
        /// </summary>
        public static string estados {
            get {
                return ResourceManager.GetString("estados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de facturas.
        /// </summary>
        public static string facturas {
            get {
                return ResourceManager.GetString("facturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de facturas.
        /// </summary>
        public static string facturascompras {
            get {
                return ResourceManager.GetString("facturascompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias.
        /// </summary>
        public static string familiasproductos {
            get {
                return ResourceManager.GetString("familiasproductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ficheros generales.
        /// </summary>
        public static string ficheros {
            get {
                return ResourceManager.GetString("ficheros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión documental.
        /// </summary>
        public static string gestiondocumental {
            get {
                return ResourceManager.GetString("gestiondocumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grosores.
        /// </summary>
        public static string grosores {
            get {
                return ResourceManager.GetString("grosores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos de Materiales.
        /// </summary>
        public static string grupomateriales {
            get {
                return ResourceManager.GetString("grupomateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos de IVA.
        /// </summary>
        public static string gruposiva {
            get {
                return ResourceManager.GetString("gruposiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guías contables.
        /// </summary>
        public static string guiascontables {
            get {
                return ResourceManager.GetString("guiascontables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albaranes.
        /// </summary>
        public static string headeralbaranes {
            get {
                return ResourceManager.GetString("headeralbaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de comisiones.
        /// </summary>
        public static string headercomisiones {
            get {
                return ResourceManager.GetString("headercomisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas.
        /// </summary>
        public static string headerfacturas {
            get {
                return ResourceManager.GetString("headerfacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos.
        /// </summary>
        public static string headerpedidos {
            get {
                return ResourceManager.GetString("headerpedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestos.
        /// </summary>
        public static string headerpresupuestos {
            get {
                return ResourceManager.GetString("headerpresupuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión imágenes de lotes.
        /// </summary>
        public static string imagenlote {
            get {
                return ResourceManager.GetString("imagenlote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lotes Imputación Costes.
        /// </summary>
        public static string imputacioncostes {
            get {
                return ResourceManager.GetString("imputacioncostes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de incidencias.
        /// </summary>
        public static string incidencias {
            get {
                return ResourceManager.GetString("incidencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencias.
        /// </summary>
        public static string incidenciascrm {
            get {
                return ResourceManager.GetString("incidenciascrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Inventarios.
        /// </summary>
        public static string inventarios {
            get {
                return ResourceManager.GetString("inventarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de kits.
        /// </summary>
        public static string kit {
            get {
                return ResourceManager.GetString("kit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listados.
        /// </summary>
        public static string listado {
            get {
                return ResourceManager.GetString("listado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de artículos.
        /// </summary>
        public static string listadoarticulos {
            get {
                return ResourceManager.GetString("listadoarticulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balance de sumas y saldos.
        /// </summary>
        public static string listadobalancesumasysaldos {
            get {
                return ResourceManager.GetString("listadobalancesumasysaldos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado CRM.
        /// </summary>
        public static string listadocrm {
            get {
                return ResourceManager.GetString("listadocrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado detallado.
        /// </summary>
        public static string listadodetalladoalbaranes {
            get {
                return ResourceManager.GetString("listadodetalladoalbaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado detallado.
        /// </summary>
        public static string listadodetalladofacturas {
            get {
                return ResourceManager.GetString("listadodetalladofacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado detallado.
        /// </summary>
        public static string listadodetalladopedidos {
            get {
                return ResourceManager.GetString("listadodetalladopedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado detallado.
        /// </summary>
        public static string listadodetalladopresupuestos {
            get {
                return ResourceManager.GetString("listadodetalladopresupuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diario contable.
        /// </summary>
        public static string listadodiariocontable {
            get {
                return ResourceManager.GetString("listadodiariocontable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado general.
        /// </summary>
        public static string listadogeneralalbaranes {
            get {
                return ResourceManager.GetString("listadogeneralalbaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado general.
        /// </summary>
        public static string listadogeneralfacturas {
            get {
                return ResourceManager.GetString("listadogeneralfacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado general.
        /// </summary>
        public static string listadogeneralpedidos {
            get {
                return ResourceManager.GetString("listadogeneralpedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado general.
        /// </summary>
        public static string listadogeneralpresupuestos {
            get {
                return ResourceManager.GetString("listadogeneralpresupuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guias de Balances.
        /// </summary>
        public static string listadoguiasbalances {
            get {
                return ResourceManager.GetString("listadoguiasbalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informe de lotes.
        /// </summary>
        public static string listadolotes {
            get {
                return ResourceManager.GetString("listadolotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de margen.
        /// </summary>
        public static string listadomargen {
            get {
                return ResourceManager.GetString("listadomargen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor.
        /// </summary>
        public static string listadomayor {
            get {
                return ResourceManager.GetString("listadomayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos en Albaranes.
        /// </summary>
        public static string listadoproductosalbaranes {
            get {
                return ResourceManager.GetString("listadoproductosalbaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos en Facturas.
        /// </summary>
        public static string listadoproductosfacturas {
            get {
                return ResourceManager.GetString("listadoproductosfacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos en Pedidos.
        /// </summary>
        public static string listadoproductospedidos {
            get {
                return ResourceManager.GetString("listadoproductospedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos en Presupuestos.
        /// </summary>
        public static string listadoproductospresupuestos {
            get {
                return ResourceManager.GetString("listadoproductospresupuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de reserv. material.
        /// </summary>
        public static string listadoreservasmaterial {
            get {
                return ResourceManager.GetString("listadoreservasmaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado Acomulado de Periodos.
        /// </summary>
        public static string listadosacomuladorperiodos {
            get {
                return ResourceManager.GetString("listadosacomuladorperiodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listados Balance Pedidos.
        /// </summary>
        public static string listadosbalancepedidos {
            get {
                return ResourceManager.GetString("listadosbalancepedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de bundles.
        /// </summary>
        public static string listadosbundles {
            get {
                return ResourceManager.GetString("listadosbundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listados de comisiones.
        /// </summary>
        public static string listadoscomision {
            get {
                return ResourceManager.GetString("listadoscomision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de kits.
        /// </summary>
        public static string listadoskits {
            get {
                return ResourceManager.GetString("listadoskits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de salidas de stock.
        /// </summary>
        public static string listadosstocksalidas {
            get {
                return ResourceManager.GetString("listadosstocksalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de stock.
        /// </summary>
        public static string listadostock {
            get {
                return ResourceManager.GetString("listadostock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado entradas almacén.
        /// </summary>
        public static string listadostockalbaranes {
            get {
                return ResourceManager.GetString("listadostockalbaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado existencias disponibles.
        /// </summary>
        public static string listadostockdisponible {
            get {
                return ResourceManager.GetString("listadostockdisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de stock valorado.
        /// </summary>
        public static string listadostockvalorado {
            get {
                return ResourceManager.GetString("listadostockvalorado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de terceros.
        /// </summary>
        public static string listadoterceros {
            get {
                return ResourceManager.GetString("listadoterceros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de control de lotes.
        /// </summary>
        public static string lotes {
            get {
                return ResourceManager.GetString("lotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formas de pago.
        /// </summary>
        public static string mantformaspago {
            get {
                return ResourceManager.GetString("mantformaspago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de retenciones.
        /// </summary>
        public static string manttiposretenciones {
            get {
                return ResourceManager.GetString("manttiposretenciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Materiales.
        /// </summary>
        public static string materiales {
            get {
                return ResourceManager.GetString("materiales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monedas.
        /// </summary>
        public static string monedas {
            get {
                return ResourceManager.GetString("monedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diario contable.
        /// </summary>
        public static string movs {
            get {
                return ResourceManager.GetString("movs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipios.
        /// </summary>
        public static string municipios {
            get {
                return ResourceManager.GetString("municipios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obras.
        /// </summary>
        public static string obras {
            get {
                return ResourceManager.GetString("obras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operarios.
        /// </summary>
        public static string operarios {
            get {
                return ResourceManager.GetString("operarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oportunidades.
        /// </summary>
        public static string oportunidades {
            get {
                return ResourceManager.GetString("oportunidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de pedidos.
        /// </summary>
        public static string pedidos {
            get {
                return ResourceManager.GetString("pedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de presupuestos.
        /// </summary>
        public static string presupuestos {
            get {
                return ResourceManager.GetString("presupuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistente de facturación.
        /// </summary>
        public static string procesofacturacion {
            get {
                return ResourceManager.GetString("procesofacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión.
        /// </summary>
        public static string produccion {
            get {
                return ResourceManager.GetString("produccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículos.
        /// </summary>
        public static string productos {
            get {
                return ResourceManager.GetString("productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prospectos.
        /// </summary>
        public static string prospectos {
            get {
                return ResourceManager.GetString("prospectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        public static string proveedores {
            get {
                return ResourceManager.GetString("proveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincias.
        /// </summary>
        public static string provincias {
            get {
                return ResourceManager.GetString("provincias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        public static string proyectos {
            get {
                return ResourceManager.GetString("proyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puertos.
        /// </summary>
        public static string puertos {
            get {
                return ResourceManager.GetString("puertos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recepciones de stock.
        /// </summary>
        public static string recepcionesstock {
            get {
                return ResourceManager.GetString("recepcionesstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Régimen de IVA.
        /// </summary>
        public static string regimeniva {
            get {
                return ResourceManager.GetString("regimeniva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de reservas.
        /// </summary>
        public static string reservas {
            get {
                return ResourceManager.GetString("reservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salidas varias.
        /// </summary>
        public static string salidasvarias {
            get {
                return ResourceManager.GetString("salidasvarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secciones analíticas.
        /// </summary>
        public static string seccionesanaliticas {
            get {
                return ResourceManager.GetString("seccionesanaliticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguimientos.
        /// </summary>
        public static string seguimientos {
            get {
                return ResourceManager.GetString("seguimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series.
        /// </summary>
        public static string series {
            get {
                return ResourceManager.GetString("series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series contables.
        /// </summary>
        public static string seriescontables {
            get {
                return ResourceManager.GetString("seriescontables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series documentos.
        /// </summary>
        public static string seriesdocumentos {
            get {
                return ResourceManager.GetString("seriesdocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Situaciones de Tesorería.
        /// </summary>
        public static string situacionestesoreria {
            get {
                return ResourceManager.GetString("situacionestesoreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        public static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablas varias.
        /// </summary>
        public static string tablasvarias {
            get {
                return ResourceManager.GetString("tablasvarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas.
        /// </summary>
        public static string tareas {
            get {
                return ResourceManager.GetString("tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifas.
        /// </summary>
        public static string tarifas {
            get {
                return ResourceManager.GetString("tarifas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terceros.
        /// </summary>
        public static string terceros {
            get {
                return ResourceManager.GetString("terceros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tesorería.
        /// </summary>
        public static string tesoreria {
            get {
                return ResourceManager.GetString("tesoreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de cuentas.
        /// </summary>
        public static string tiposcuentas {
            get {
                return ResourceManager.GetString("tiposcuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de IVA.
        /// </summary>
        public static string tiposiva {
            get {
                return ResourceManager.GetString("tiposiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajos.
        /// </summary>
        public static string trabajos {
            get {
                return ResourceManager.GetString("trabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de transformaciones.
        /// </summary>
        public static string transformaciones {
            get {
                return ResourceManager.GetString("transformaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transformaciones de acabados.
        /// </summary>
        public static string transformacioneslotes {
            get {
                return ResourceManager.GetString("transformacioneslotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportistas.
        /// </summary>
        public static string transportistas {
            get {
                return ResourceManager.GetString("transportistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de traspasos de almacén.
        /// </summary>
        public static string traspasosalmacen {
            get {
                return ResourceManager.GetString("traspasosalmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades de medida.
        /// </summary>
        public static string unidades {
            get {
                return ResourceManager.GetString("unidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previsión de pagos.
        /// </summary>
        public static string vencimientoscompra {
            get {
                return ResourceManager.GetString("vencimientoscompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previsión de cobros.
        /// </summary>
        public static string vencimientosventa {
            get {
                return ResourceManager.GetString("vencimientosventa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        public static string ventas {
            get {
                return ResourceManager.GetString("ventas", resourceCulture);
            }
        }
    }
}
